### ISSUE TITLE
waitForHealthyStateTimeout only apply to unhealty

### ISSUE THREAD

**Issue by matthewrj** [avast/gradle-docker-compose-plugin#100]
The current implementation ignores the transition from starting to unhealthy. This makes the retries parameter in the docker compose health check do nothing. I think it would make more sense if the timeout applied from the time the container became unhealthy. waitForHealthyStateTimeout could even be considered redundant as you could make (interval * retries) equal what you originally used for waitForHealthyStateTimeout if the task exits once a container becomes unhealthy.

**Comment by augi** [comment]
I'm not sure if I completely understand this issue :(

The `waitForHealthyStateTimeout` is simply the timeout when the container should become healthy (ignoring possible healthy-state transitions).

Maybe it would be easier if you demonstrated your intents using a new PR - you probably want to change [this method](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L280)

**Comment by augi** [comment]
I got your point - the measurement of the timeout should start after the container leaves the `starting` state, according to you.

I think it's better to measure this timeout from the point after `docker-compose up` command exits. I've just made minor tweaks to measure this period more precisely #107
