### ISSUE TITLE
plugin error in mac

### ISSUE THREAD

**Issue by danielezer** [avast/gradle-docker-compose-plugin#113]
Hi, is there any way to keep the containers running after the task has finished running?

**Comment by augi** [comment]
Yes:
```gradle
dockerCompose {
    stopContainers = false
}
```
It causes that `docker-compose down` is not called.

**Comment by danielezer** [comment]
Cool! Thanks

and if I want to just stop them from another task?

**Comment by augi** [comment]
The plugin adds `composeDown` task so you can ensure that this task is called.

**Comment by augi** [comment]
If you want to call the `composeDown` explicitly (I cannot recommend it) then you can call something like this: `tasks.composeDown.down()` (`down()` is the main method of `ComposeDown` task).

**Comment by danielezer** [comment]
Nice! 
Thanks you for the quick reply :)
