### ISSUE TITLE
Could not find method getServiceLogs()

### ISSUE THREAD

**Issue by dstepanov** [avast/gradle-docker-compose-plugin#121]
At some point when exception occurred plugin is failing with:
```
Could not find method getServiceLogs() for arguments [638ac5981a99cf160613326601b221d4d74a86fccde3564a5ba281399d98cc3e] on task ':stacks:pos-es:composeUp' of type com.avast.gradle.dockercompose.tasks.ComposeUp.
```
Because there is no `getServiceLogs` in `com.avast.gradle.dockercompose.tasks.ComposeUp`

**Comment by augi** [comment]
Will be released as `0.6.5` in few minutes. Sorry for any inconvenience.

**Comment by dstepanov** [comment]
Thanks, it only happened when something went wrong anyway

**Comment by augi** [comment]
Yep, IDEA didn't updated the usage when I renamed the method :(
