### ISSUE TITLE
Nested Configuration Issue

### ISSUE THREAD

**Issue by mattupstate** [avast/gradle-docker-compose-plugin#130]
In trying to use this nested configuration as illustrated by the README.md I get a `String index out of range: 1` error. For example:

```
dockerCompose {
    bootRun {
        stopContainers = false
        useComposeFiles = ['docker-compose.dev.yml']
        startedServices = ['postgres']
        isRequiredBy(bootRun)
    }
}
```

**Comment by augi** [comment]
It's strange because this case is covered by unit-tests. Could you please execute your Gradle project with `-S` argument to get stacktrace of that error? Thanks!

**Comment by augi** [comment]
I got it. The problem is that `bootRun` is not recognized as a `Task`. So please write `tasks.bootRun` instead please - I've updated the README.

Thanks for the report and feel free to reopen this issue if it won't work.

**Comment by mattupstate** [comment]
@augi thanks!
