### ISSUE TITLE
Inconsistent documentation  with Gradle portal

### ISSUE THREAD

**Issue by tkruse** [avast/gradle-docker-compose-plugin#132]
Hi, the README currently states

```
buildscript {
...
    dependencies {
        classpath "com.avast.gradle:gradle-docker-compose-plugin:$versionHere"
    }
}

apply plugin: 'docker-compose'
// Or use the new Gradle Portal plugins:
// plugins {
//  id 'com.avast.gradle.docker-compose' version "$versionHere"
// }
```

But gradle portal has a different classpath (https://plugins.gradle.org/plugin/com.avast.gradle.docker-compose

```
dependencies {
    classpath "gradle.plugin.com.avast.gradle:gradle-docker-compose-plugin:0.6.9"
  }
```

This is a bit confusing, maybe the comment in README can be clarified more?

**Comment by augi** [comment]
Thanks! The plugin is published to both jcenter and Gradle portal so also the `classpath` works. If you import the plugin then you don't have to add any `classpath`. I've tried to clarify it in the README.
