### ISSUE TITLE
--exit-code-from and -d are mutually exclusive

### ISSUE THREAD

**Issue by HSZemi** [avast/gradle-docker-compose-plugin#135]
If `settings.exitCodeFromService` is used, `composeUp` will fail, as it is always called with `-d`.

```bash
$ docker-compose up -d --exit-code-from dummy_c dummy_a dummy_b dummy_c
WARNING: using --exit-code-from implies --abort-on-container-exit
ERROR: --abort-on-container-exit and -d cannot be combined.
```

See also: [https://docs.docker.com/compose/reference/up/](https://docs.docker.com/compose/reference/up/)

**Comment by augi** [comment]
Thank you, the fix will be released ASAP.
