### ISSUE TITLE
'tasks' is not property nor nested settings name

### ISSUE THREAD

**Issue by fabienrenaud** [avast/gradle-docker-compose-plugin#137]
I am trying to set up a nested compose task and make it a requirement on my tests. I copied the example code from the readme: https://github.com/avast/gradle-docker-compose-plugin#nested-configurations 

```
dockerCompose {
    myTest {
        useComposeFiles = ['src/test/resources/mysql.yml']
        startedServices = ['mysql']
        environment.put 'MYSQL_ROOT_PASSWORD', 'root_password'
        isRequiredBy(tasks.test)
    }
}
```

and when i run `gradle test`, or `gradle myTestComposeUp`, I immediately get this message from gradle:
```
'tasks' is not property nor nested settings name
```
which seems to be coming from here: https://github.com/avast/gradle-docker-compose-plugin/blob/494e9e70299d295704e61c7d50c651233ee6f167/src/main/groovy/com/avast/gradle/dockercompose/ComposeExtension.groovy#L17

What am I doing wrong? Is this a bug?

Note that I can get the container to start successfully with `myTestComposeUp` if I remove the isRequiredBy.

Versions:
 * docker-compose-plugin 0.6.12
 * gradle 4.4
 * mac osx sierra

**Comment by augi** [comment]
Unfortunately, you have to write `project.tasks.test` - I fixed the example in README.

If you have an idea how to overcome this issue in a nicer way, feel free to reopen this ticket.
