### ISSUE TITLE
Possible to run build with out composeUp

### ISSUE THREAD

**Issue by mlmeyers** [avast/gradle-docker-compose-plugin#138]
Is there any way to run the build with out composeUp. It seems that if I want to build the containers with this plugin I have to invoke the composeUp task. I would like to have separate task to just build the containers. Is this possible? 

Ideally I would have tasks for Pull,Build,Up,Down. if not this would prove very useful as there are times i want to build and not start the containers. 

Overall very pleased with this plugin, very slick thanks for contributing!

**Comment by augi** [comment]
Hi! The plugins now offers `composeUp`, `composeDown` and `composePull` tasks. So it makes sense to have `composeBuild` as well.

**Comment by augi** [comment]
Released as `0.6.14`. Btw. `composePull` also builds the image.

**Comment by mlmeyers** [comment]
Works great! Thanks for the quick turn around Michal 🥇
