### ISSUE TITLE
composeDown failing if another process is running

### ISSUE THREAD

**Issue by avillev** [avast/gradle-docker-compose-plugin#139]
Env: Windows 10, Gradle 4.5.1

It seems that, if another container is till running in docker and if the option removeOrphans = false, the composeDown fails with a:

`Removing docker_kafka_1     ... done
Removing docker_mysql_1     ... done
Removing docker_redis_1     ... done
Removing docker_zookeeper_1 ... done
Removing network docker_default
network docker_default id f1b4dc85ae52aa5a0bee008165522325833471316dbf7cc171bc8cffb5b5177b has active endpoints
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':controller:composeDown'.
> Process 'command 'docker-compose'' finished with non-zero exit value 1`

I do not wish to remove orphans. What could be done for this problem ? Using a different network for each cocker-compose.yml ?

**Comment by avillev** [comment]
What you say totally makes sense.
Except when the docker-compose.yml does not define any network and the containers will use the default network which may be used by other containers. Or if any other container use the same network i guess but that is, maybe, another problem.

**Comment by augi** [comment]
Agree, if `docker-compose` tries to remove network that is not defined in the yaml file then it's strange.

If you observe this behavior then you could report it to `docker-compose` project, I'm afraid I cannot do anything with this issue :(

**Comment by avillev** [comment]
Ha ok, it is the docker-compose command which does this, not you. Then my bad.

**Comment by augi** [comment]
Yep. Actually this Gradle plugin just calls the `docker-compose` commands 😄

**Comment by avillev** [comment]
That i knew 👍 
But i did not know that the network removal was automatic while executing a docker-compose stop
