### ISSUE TITLE
Speed up run when the containers are already running

### ISSUE THREAD

**Issue by geowarin** [avast/gradle-docker-compose-plugin#142]
Hello,

I love the plugin thank you so much !

In my current setup, I like to keep the container running because it is also used by the dev environment.

```gradle
dockerCompose {
  stopContainers = false
  upAdditionalArgs = ['--no-recreate']
}
```

I did not find any way to speed up the build when the containers are already running.

Ideally, when the service is already running and healthy, it should not be necessary to run any more commands.

Do you think it is possible ?
Maybe I could do it manually in my gradle config ?

Thanks !

**Comment by augi** [comment]
Hi, if you have `stopContainers` set to `true` then no command is invoked, [see the code](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeDown.groovy#L19). And if you have `--no-recreate` specified for the `up` command then it's IMHO maximum what you can do for best performance :(

Could you provide us with the log what's happening? I think that the `up` just checks if the containers are running and skip their initialization. Maybe we could try to list running containers using [docker-compose ps](https://docs.docker.com/compose/reference/ps/) and if all the containers are running, then don't call `up` (it would be change around [this line](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L50)).

I'm afraid that the performance would be almost the same as calling `up` but feel free to measure it. The scenario would be:
1. Start the project so the containers are running.
2. Execute `composeUp` and measure the execution duration.
3. Execute `docker-compose ps` and again measure the execution duration. You could call something like `dockerCompose.composeExecutor.execute('ps')`.

**Comment by geowarin** [comment]
Here is the log:

<details>
```
Selected primary task 'composeUp' from project :
Tasks to be executed: [task ':data-model:composeUp']
:data-model:composeUp (Thread[Task worker for ':',5,main]) started.

> Task :data-model:composeUp 
Task ':data-model:composeUp' is not up-to-date because:
  Task has not declared any outputs.
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml build
Successfully started process 'command '/usr/local/bin/docker-compose''
postgres uses an image, skipping
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml --version
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml --version
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml up -d --no-recreate
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting bootreactgraphql_postgres_1 ... done
> :data-model:composeUp                                             Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml --version
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml config --services
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml ps -q postgres
Successfully started process 'command '/usr/local/bin/docker-compose''
Container ID of service postgres is 77eb3ae909812afbc0c594aff55ff11253d022152f7a9c5d4482f6b43d31b955
Starting process 'command '/usr/local/bin/docker''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker inspect 77eb3ae909812afbc0c594aff55ff11253d022152f7a9c5d4482f6b43d31b955
Successfully started process 'command '/usr/local/bin/docker''
Will use localhost as host of postgres
Will use com.avast.gradle.dockercompose.ServiceHost(localhost, LocalHost) as host of service postgres
Exposed TCP port on service 'postgres:5432' will be available as 5432
Starting process 'command '/usr/local/bin/docker''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker inspect 77eb3ae909812afbc0c594aff55ff11253d022152f7a9c5d4482f6b43d31b955
Successfully started process 'command '/usr/local/bin/docker''
postgres_1 health state reported as 'healthy' - continuing...
Probing TCP socket on localhost:5432 of service 'postgres_1'
TCP socket on localhost:5432 of service 'postgres_1' is ready

:data-model:composeUp (Thread[Task worker for ':',5,main]) completed. Took 6.535 secs.
```
</details>

I hoping that running `docker inspect` / `docker ps` before calling `compose up` would speed up the process.

I've had a chance to look a the code since I posted the issue. 
I will measure this tomorrow and keep you posted.

Thanks for your anwser

**Comment by geowarin** [comment]
Docker-compose ps is a bit faster!

```
> Task :data-model:ps 
Name                          Command              State           Ports         
--------------------------------------------------------------------------------------------
bootreactgraphql_postgres_1   docker-entrypoint.sh postgres   Up      0.0.0.0:5432->5432/tcp


BUILD SUCCESSFUL in 1s
```

**Comment by geowarin** [comment]
Here is what I came up with:

```gradle
def composeServicesRunning() {
  String ps = dockerCompose.composeExecutor.execute('ps')
  def services = ps.readLines().drop(2)
  return !services.isEmpty() && services.every { it.contains("Up")}
}

composeUp.onlyIf {
  !composeServicesRunning()
}
```

Do you want to add support for that in the plugin or is this out of scope ?

**Comment by augi** [comment]
Thanks for your help!

As I'm looking to the log you submitted, there are 3 calls to `docker-compose --version` so I've just introduced caching of this value (because I don't expect that `docker-compose` version would change during one Gradle run).

I've just released `0.6.15` with this improvement. It should save you 2 calls.

One more call could be save in your case - omit the `docker-compose build` step. So please set `buildBeforeUp` parameter to `false`.

I believe the start should be faster after these changes.

Btw. calling `ps` before `up` (and potentially don't call the `up`) would be IMHO almost the same in performance PoV, but the complexity would be increased significantly. We would have to perform more checks that just call the `ps`, e.g. list all the services (to check if all are running).

So please let me know how the proposed changes helped.

**Comment by geowarin** [comment]
Thanks @augi !
Here is the log with the new version of the plugin and `buildBeforeUp` set to false.

<details>

```
> Task :data-model:composeUp 
Task ':data-model:composeUp' is not up-to-date because:
  Task has not declared any outputs.
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml version --short
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml up -d --no-recreate
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting bootreactgraphql_postgres_1 ... done
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml config --services
Successfully started process 'command '/usr/local/bin/docker-compose''
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml ps -q postgres
Successfully started process 'command '/usr/local/bin/docker-compose''
Container ID of service postgres is 11b9cc323a74415adfb8ddbb102e24ac3d927061add7c6bcd9dea661b80cad2b
Starting process 'command '/usr/local/bin/docker''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker inspect 11b9cc323a74415adfb8ddbb102e24ac3d927061add7c6bcd9dea661b80cad2b
Successfully started process 'command '/usr/local/bin/docker''
Will use localhost as host of postgres
Will use com.avast.gradle.dockercompose.ServiceHost(localhost, LocalHost) as host of service postgres
Exposed TCP port on service 'postgres:5432' will be available as 5432
Starting process 'command '/usr/local/bin/docker''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker inspect 11b9cc323a74415adfb8ddbb102e24ac3d927061add7c6bcd9dea661b80cad2b
Successfully started process 'command '/usr/local/bin/docker''
Probing TCP socket on localhost:5432 of service 'postgres_1'
TCP socket on localhost:5432 of service 'postgres_1' is ready

:data-model:composeUp (Thread[Task worker for ':',5,main]) completed. Took 4.286 secs.
```

</details>

4.286 secs. That's a 2 seconds improvement, not bad :)

When calling `compose ps` before running `up`:

<details>

```
All projects evaluated.
Selected primary task 'composeUp' from project :
Tasks to be executed: [task ':data-model:composeUp']
:data-model:composeUp (Thread[Task worker for ':',5,main]) started.

> Task :data-model:composeUp SKIPPED
Starting process 'command '/usr/local/bin/docker-compose''. Working directory: /Users/geowarin/dev/new-pro/boot-react-graphql/modules/data-model Command: /usr/local/bin/docker-compose -f ../../docker-compose.yml ps
Successfully started process 'command '/usr/local/bin/docker-compose''
Skipping task ':data-model:composeUp' as task onlyIf is false.

:data-model:composeUp (Thread[Task worker for ':',5,main]) completed. Took 0.796 secs.

BUILD SUCCESSFUL in 1s
```

</details>

The project taks 1s overall (not just composeUp). So it is still a significant improvement.

I agree that implementing this would add more complexity.
The `onlyIf` method I posted is more of an heuristic than a real implementation (it skips health check and port check).
It is trading correctness for speed.

I'm closing this as I reckon that you have implemented the best solution while keeping the spirit of the plugin (ensuring that containers are ready and healthy).

Feel free to reopen it if you are thinking of including a flag like 'unsafeCheckRunning', I could help with the implementation.

**Comment by augi** [comment]
Cool, thank you for your input! It showed me that the performance can be an issue and I should focus on it as well.

**Comment by augi** [comment]
Btw. we could save one more command line execution by merging `docker inspect` calls, see #144

**Comment by geowarin** [comment]
No problem!

I guess I forgot to give your more details about my use case:

I'm running postgres and then code generation with jooq (which needs to connect to the database). 
The task is bound to be called often (like every time you modify sql files) so shaving a few seconds here and there is really a quality-of-life thing.

All of the other tasks benefit from gradle increment compilation and up-to-date checks so it seems logical to do so with docker-compose.

**Comment by augi** [comment]
I've made some further improvements related to performance - check the last release. I've also created #145 - it's actually your original idea.

**Comment by augi** [comment]
I've just released [0.7.0](https://github.com/avast/gradle-docker-compose-plugin/releases/tag/0.7.0) that implements the _reconnecting_. It's automatically enabled when you set `stopContainers` to `false`.

**Comment by geowarin** [comment]
This is awesome ! 😍

**Comment by geowarin** [comment]
Just tested it and it works like magic.
I think it makes a ton of sense to try and reconnect if `stopContainers` is false.

@augi, you're an awesome open-source maintainer. Thank you for your work 🥇

**Comment by geowarin** [comment]
Aren't you worried about the potential breaking change if someone was previously calling `composeDown` manually with `stopContainers=false` ?

**Comment by augi** [comment]
If someone called `composeDown` with `stopContainers` set to `false` then the task didn't do anything. And it's still the same.

I've just added `composeDownForced` task that performs `docker-compose down` always (it doesn't check `stopContainers`).

So this shouldn't be a breaking change IMHO.
