### ISSUE TITLE
Feature request add support for build params with composeBuild

### ISSUE THREAD

**Issue by mlmeyers** [avast/gradle-docker-compose-plugin#148]
When building in CI it seems a common practice to pull to be sure you are getting the latest from the remote repo when building. Still coming up to speed on docker but it appears the behavior between compose pull, and compose build --pull differ. 

compose build --pull seems to update my base images inside my docker file before building and does not try to pull the image being built. 

compose pull seems the actual image is pulled and will reset the entire image local with the latest in the repo. Seems better for deployments and not builds. Will error on a local built image with no remote defined. 

compose up --build would be great however it does not have a option to pull before build so will not pull in changes to base images.

This is what I gather so far but could be off in my assumptions. 

Does anyone have experience using this plugin and compose in a CI/CD pipeline that could shed light on a robust pattern to build and deploy ? I am struggling to find a good example.

In my CI/CD process I believe I want (I am using containers for integration testing and environment deployments). :

Build:
1. docker-compose build --pull (compose file builds local images, example mongo:latest)
2. docker-compose up 
3. run integration tests
4. docker-compose down
5. docker tag (tag with remote repo, example myorg/mongo:1.0.gitsha)
6. docker push
7. Remove local tag (myorg/mongo:1.0.gitsha)

Environment Deploy:
1. docker-compose pull (myorg/mongo:1.0.gitsha)
2. docker-compose up --force-recreate

To support this would need composeBuild to accept the built in params. 
 --force-rm                       Always remove intermediate containers 
 --no-cache                      Do not use cache when building the image.
 --pull                               Always attempt to pull a newer version of the image.
 -m, --memory MEM        Sets memory limit for the bulid container.
 --build-arg key=val         Set build-time variables for one service.

composeUp with buildBeforeUp would ideally just call the composeBuild and use the specified settings buildParams. 

I am not clear on why the docker guys added build and pull support to multiple commands. I assume a cry for convenience but seems to me it muddies the waters a bit. 

Sorry for rambling, just trying to wrap my head around how to fit this plugin and docker into a CI/CD process. 

Any comments, thoughts on the above are very much appreciated !

Cheers.

**Comment by augi** [comment]
I've never had this kind of issue. IMHO the best practice is not to use the `latest` tag, even for base images. And never change already existing `tag`. Then all the builds and deployment are repeatable and you don't have to tackle with some cached versions etc.

Anyway, I've just released `0.7.1` that allows to specify additional arguments also for `build`, `pull` and `down` commands, so hopefully also your use-case is supported now.

**Comment by mlmeyers** [comment]
Thanks Augi! Was just seem reads I had encountered with a few folks burned by not pulling before build on CI. That said I agree on your points around not using latest. Thanks for the features, no doubt having the flexibility to tweak the params on build, pull, and down will prove useful. 

Cheers!
