### ISSUE TITLE
Container is returning exit code 1 but build is successful 

### ISSUE THREAD

**Issue by yeikel** [avast/gradle-docker-compose-plugin#149]
I have the following containers : 

1 - API
2 - API-TEST

API-test is running integration tests that may return an exit code > 0 when they fail . 

The issue that I am facing is that plugin is returning a successful build : 

For example : 

```
api-test_1  |  1.  AssertionError  expected '{"id":3,"content":"Hello, World"}' to include 'Hello1, World'
api-test_1  |                      at assertion:0 in test-script
api-test_1  |                      inside "greeting"
fantasyfutbol_api-test_1 exited with code 1
api_1       | 2018-04-10 23:55:25 - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@73035e27: startup date [Tue Apr 10 23:55:07 UTC 2018]; root of context hierarchy
Stopping fantasyfutbol_api-test_1 ... done

> Task :composeDown

api_1       | 2018-04-10 23:55:26 - Unregistering JMX-exposed beans on shutdown
fantasyfutbol_api_1 exited with code 143
Stopping fantasyfutbol_api_1      ... done
> Task :composeDown
Removing fantasyfutbol_api-test_1 ... done
Removing fantasyfutbol_api_1      ... done
Removing fantasyfutbol_db_1       ... done
Removing network fantasyfutbol_default
Removing volume fantasyfutbol_db-data


BUILD SUCCESSFUL in 32s
```

Edit: I saw this was discussed and fixed in #80. It is there any way to bring this back?

> Thanks! I'm not able to reproduce this so I've just changed the code to ignore the exit-code if the process is executed from background thread. It's released as 0.6.13, hope it helps.

**Comment by augi** [comment]
Hi,

this is not an issue with this plugin, but with Docker Compose itself. It returns exit-code 0 if the containers are properly started. According to your log, they was properly started so Docker Compose returned `0`. Your container failed later.

I don't know your use case but in general, there are two solutions.

If the failing container is a _main_ service (e.g. application, while other containers are just databases) then you could use an additional parameter for `docker-compose up` command, called [--exit-code-from](https://docs.docker.com/compose/reference/up/).

If you have more containers with equal importance, then I would suggest to define a healthcheck. It can be defined [in Dockerfile](https://docs.docker.com/engine/reference/builder/#healthcheck) or [in docker-compose.yml](https://docs.docker.com/compose/compose-file/#healthcheck).

The healthcheck should check if your application is running correctly.

Hope it helps.

**Comment by yeikel** [comment]
@augi How can I pass the exit-code parameter to this plugin?

**Comment by augi** [comment]
You can pass an additional parameter for `docker-compose up` using `upAdditionalArgs`, e.g. `upAdditionalArgs = ['--exit-code-from', 'e2etest']`.

In your particular use-case, I would recommend to use the `--exit-code-from` as shown above.

The plugin doesn't monitor health of the containers - it cannot because its lifetime is limited to the containers execution. The plugin just starts the containers and wait until all become healthy.

**Comment by yeikel** [comment]
@augi Thank you for your continuous support. 

Do you know why I am getting this? 

```
using --exit-code-from implies --abort-on-container-exit
--abort-on-container-exit and -d cannot be combined.
```

**Comment by yeikel** [comment]
@augi Once again, thank you for getting back me one more time and for providing me your insight. 

As part of my build, I have the following setup : 

- Start the database (In Docker)
- Deploy and launch the API(also in Docker)
- Integration tests

The integration tests, are postman scripts that run after the Database and the API are ready to serve requests. Right now, I am running the tests from the host machine targetting localhost: mapped port, and grade seems to catch the errors just fine. 

The main challenge I have is that postman needs a NodeJS runtime for which I am using another Gradle plugin to manage. My ideal goal is to put the tests in a docker image so I can remove that dependency and also use the networking that docker provides me (call API: port and reduce port issues that happen on the host)

**Comment by augi** [comment]
This plugin is perfect match for your original solution (DB and API in containers, _native_ tests). Just please note that you don't have to hard-wire `localhost` and mapped port, you could take advantage of `exposeAsEnvironment` method as described in the README.

If you are going to move also your tests to a container, then this plugin is useless IMHO. I would probably prepare `docker-compose.yml` like this:
```yaml
version: "3"
  services:
    db:
      image: postgres:9.6
      ports:
        - "5436"
    api:
      dockerfile: Dockerfile-api
      ports:
        - "80"
      environment:
         MY_DB: "db:5436"
    tests:
      dockerfile: Dockerfile-tests
      environment:
        MY_API: "api:80"
```
And then execute `docker-compose up  --exit-code-from tests`.

You could take advantage of [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) in your Dockerfiles. E.g. the first stage would use `gradle` Docker image, and this stage would produce artifacts. Then you could copy these artifacts to the second (runtime) stage.

The only thing that you should solve in this solution is waiting for the API and DB services to become healthy (it's done by this plugin).
