### ISSUE TITLE
How can I force docker-compose down?

### ISSUE THREAD

**Issue by yeikel** [avast/gradle-docker-compose-plugin#150]
I have a use case where I'd like to : 

1 - Call docker-compose up
2 - Work on my application and export the database modifications back to my host
3 - Call docker-compose down

Currently, what is happening is : 

1 - Call docker-compose up
2 - Work on my application
3 - Some images stay in memory (such as the database) 

I tried to 

```
dockerCompose.dependsOn(composeDownForced)
dockerCompose.isRequiredBy(task)
```
 But that did not seem to work

**Comment by yeikel** [comment]
If I am not mistaken , this seems to be the solution : 

```
    task.dependsOn(composeDownForced)
    dockerCompose.isRequiredBy(task)
```

I am leaving the issue open to confirm with you.

Thank you!

**Comment by augi** [comment]
You can have just `dockerCompose.isRequiredBy(task)`. It performs `dependsOn` and `finalizedBy`, as seen [here](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L119).

**Comment by yeikel** [comment]
@augi I don't think it is calling docker-compose down if I do what you suggested

**Comment by augi** [comment]
It does, provided you didn't set `stopContainers` to `false` (default is `true`).

Could you please provide us with Gradle log and your plugin settings?
