### ISSUE TITLE
Plugin fails due to stopped container.

### ISSUE THREAD

**Issue by michaelruocco** [avast/gradle-docker-compose-plugin#153]
Hi,

I have been looking into using this plugin in a project of mine and it works very well aside for one niggling problem.

My project contains a compose template with 3 containers, one is a mongo DB, the other is another mongo container, but its job is simply to seed data into the mongo DB container, it runs a mongo import script and then stops. Finally the third is a container running a spring boot app that uses the mongo DB.

The problem I have is that the container that is seeding the data stops once it has done its job. However the plugin is failing because it is expecting the container to be running. The error that I see in the output is:

```
These ports of service skeleton-test-data are declared as exposed but cannot be found in NetworkSettings: 27017/tcp\n[Id:f1021471a99c2c4bbdbcf4d9e34acedd282b7197aa647c085f8a12bc222171cb, Created:2018-05-08T05:15:09.3801182Z, Path:docker-entrypoint.sh, Args:[/bin/sh, -c, mongoimport --host $MONGO_HOST --db $MONGO_DATABASE --collection mongoCustomer --type json --file /init.json --jsonArray], State:[Status:exited, Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:, StartedAt:2018-05-08T05:15:10.0623461Z, FinishedAt:2018-05-08T05:15:10.1903606Z], .....
```

As you can see from the output above the container has an ExitCode of 0 so has completed okay, the issue is that it simply does not run for very long (which is what I intended.)

I have managed to resolve the issue locally by adding a bit of a hacky fix:

```
    void validateInspection(String serviceName, Map<String, Object> inspection) {
        logger.info('****************************** VALIDATING INSPECTION FOR SERVICE ' + serviceName)
        ServiceHost serviceHost
        try {
            serviceHost = getContainerHost(inspection, serviceName, NoOpLogger.INSTANCE)
        } catch (Exception e) {
            throw new RuntimeException("Error when getting service host of service $serviceName: ${e.message}\n${inspection.toString()}", e)
        }
        //I have added additional check below for if the container has exited, don't bother checking
        //for missing ports
        if (serviceHost.type != ServiceHostType.Host && inspection.State.Status != 'exited') {
            Map<String, Object> portsFromConfig = inspection.Config.ExposedPorts ?: [:]
            logger.info("ports from config " + portsFromConfig)
            Map<String, Object> portsFromNetwork = inspection.NetworkSettings.Ports
            logger.info("ports from network " + portsFromNetwork)
            def missingPorts = portsFromConfig.keySet().findAll { !portsFromNetwork.containsKey(it) }
            logger.info("missing ports " + missingPorts)
            if (!missingPorts.empty) {
                throw new RuntimeException("These ports of service $serviceName are declared as exposed but cannot be found in NetworkSettings: ${missingPorts.join(', ')}\\n${inspection.toString()}")
            }
        }
    }
```

I have mainly done this to prove that it would solve my problem. I thought a better fix would be to allow the user to specify another configuration option where they could provide a list of container names to ignore/skip the the call to validate inspection.

I was hoping to get your view / opinion before spending time doing the work to raise a PR though. As I was hoping that I might be missing another simpler way around the problem. My other thought was if I could run the mongo import inside a container that didn't expose a port that would probably fix the issue too, but I didn't really want to have to create my own container to solve this problem as it works fine when running docker-compose up manually.

What do you think?

**Comment by michaelruocco** [comment]
After raising this issue I decided to have a go at creating my own container which didn't expose the port I didn't need. It was very quick and probably a much simpler solution to this problem. So I am going to close this issue again.

**Comment by augi** [comment]
The container doesn't have to run in general. But if it declares that it offers a TCP port then it should be running :)

So it's really better to create a container that doesn't expose any port. It would be nice if it were possible to un-EXPOSE a TCP port, see [this issue](https://github.com/moby/moby/issues/3465).

**Comment by michaelruocco** [comment]
Yeah I had come across that issue when looking at other ways to solve the problem. I have gone with creating a new container that doesn't expose a port for now. Thanks for the info.

**Comment by yngvark** [comment]
@augi An issue is that it is quite common to use third party images that we have no control of. Creating my own image that doesn't expose ports is not a good solution in my opinion, because then we have to maintain it for all future if we want updates from the original image.

Also, quoting from the [dockerfile reference](https://docs.docker.com/engine/reference/builder/):

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published

In my opinion, one should look at EXPOSE as a comment, not as anything functional that does anything. Hence, using it as a part of a forced validation feels wrong to me. Is it possible to have an option to skip the validation as part of the configuration perhaps?

**Comment by augi** [comment]
@yngvark, the `validateInspection` method just validates consistency of the output from `docker inspect` command.

I see two solutions to your objectives:

1. Allow to skip validation for selected services/containers.
2. Remove this validation completely.

I would prefer to do 2 as purpose of this plugin is not to check if Docker is corrupted. Do you agree?

**Comment by yngvark** [comment]
I suppose the validation was added for a reason, but I agree with your point.
