### ISSUE TITLE
Add option to allow declared host ports in compose file, but ignore when runnning in integration mode

### ISSUE THREAD

**Issue by checketts** [avast/gradle-docker-compose-plugin#154]
I want my composed up services to run on random ports (I love that feature!), however, when developing it is nice to be able to expect my database and other services to be on predictable ports.

Currently I end up having 2 compose files: one for when I start compose myself and one for integration tests. The integration test file is identical except for not declaring ports.

Is there a way to use the same compose file, but have the integration test mode enable the random ports?

**Comment by augi** [comment]
`docker-compose` command supports specifying more files using [-f option](https://docs.docker.com/compose/reference/overview/) - these files are then combined. Also this plugin supports this feature via `useComposeFiles` property (array of files to use).

So you could have a `docker-compose.yml` without the ports specified, and then `docker-compose.local.yml` that just adds the specific port.
You would use just the `docker-compose.yml` for integration tests, and both files for local development.

Hope it helps.

**Comment by checketts** [comment]
Thanks for the answer. I like how it uses the existing compose behavior. Here is a further example I found with examples demonstrating what you described: https://mindbyte.nl/2018/04/04/overwrite-ports-in-docker-compose.html (in case others find this issue later and are curious)
