### ISSUE TITLE
Problem with output

### ISSUE THREAD

**Issue by cecton** [avast/gradle-docker-compose-plugin#167]
The problem
=========

I tried to run a ComposeUp and the command failed without giving me useful information. When I tried to run the command by hand I realized that a port was already taken and that was the actual reason of the failure.

The origin
=======

I noticed that the plugin doesn't use the `--no-ansi` parameter by default. Because of that, some logs get overridden because of the manipulation on the tty with the ansi codes.

The solutions
==========

I think it would be best to use `--no-ansi` by default but if you had a parameter that allows to configure the arguments given to the docker-compose command (the ones **before** the first positional parameter) it would probably be more flexible.

Example of those commands:

```
docker-compose --no-ansi up -d
```

I don't mind to do a PR to do either of these solutions but I don't know groovy at all. I don't mind learning.

Let met know if it's okay to implement one of these solutions.

**Comment by augi** [comment]
Thanks for this suggestion! I implement this feature and is available in `0.8.5`.

**Comment by cecton** [comment]
That was fast 👍 thanks a lot!
