### ISSUE TITLE
Need to exclude specific ports from waitForTcpPorts 

### ISSUE THREAD

**Issue by recumbent** [avast/gradle-docker-compose-plugin#168]
We want to spin up multiple containers in a test scenario.

The problem is that one of the ports that's exposed (for [mountebank](http://www.mbtest.org)) won't respond to the wait for ports check because its not been configured to respond.

Accordingly one would like to exclude that port (or ports) from the startup wait. Generically the check is useful to ensure that our service and mountebank are running but in context we can never get past that point if we have the checks enabled because that specific port won't ever respond.

**Comment by recumbent** [comment]
I may be able to take a look at this in which case I have a "naming of things" challenge but the config value would be something like:

```
    tpcPortsToIgnoreWhenWaiting = [ 4545 ] 
```

**Comment by augi** [comment]
It would be nice if we wouldn't have to add this feature to this plugin, e.g. solve the problem using some Dockerfile of Docker Compose feature (`UNEXPOSE` doesn't exist btw. 😄).

If it's not really possible I can prepare a MR next week. `tpcPortsToIgnoreWhenWaiting` property name is OK for me.

**Comment by recumbent** [comment]
> It would be nice if we wouldn't have to add this feature to this plugin, e.g. solve the problem using some Dockerfile of Docker Compose feature (`UNEXPOSE` doesn't exist btw. 😄).

Absolutely would be nice... but I think in this case we have a mismatch between reasonable assumptions and our specific use case. Change doesn't look too awkward (I bet I have more "fun" writing tests than addressing the problem) and its probably a nice feature to have.

**Comment by augi** [comment]
Agree, I will try to release this change later today (CET).

**Comment by recumbent** [comment]
Also I can't type... I suspect "tcpPorts" would be better than "tpcPorts" 🤦‍♂️

**Comment by augi** [comment]
`0.8.8`
