### ISSUE TITLE
tcpPortsToIgnoreWhenWaiting doesn't work with composed configuration

### ISSUE THREAD

**Issue by Jazzepi** [avast/gradle-docker-compose-plugin#174]
This works when bringing up the stack with prodComposeUp
```
dockerCompose {

    dev {
    }
    prod {
        tcpPortsToIgnoreWhenWaiting = [33333]
    }
}
```

This does NOT work when bringing up the stack with prodComposeUp
```
dockerCompose {

    dev {
    }
    prod {
    }
    tcpPortsToIgnoreWhenWaiting = [33333]
}
```

**Comment by augi** [comment]
Thanks for the report! Some of parameters weren't copied so I fixed that.

Also please note that `tcpPortsToIgnoreWhenWaiting` defined in the top-level object must be specified *before* the nested configurations. I've added a note about this behavior into README.

The fix will be released in few minutes.
