### ISSUE TITLE
add an option to fetch container logs before remove it when composeUp failed

### ISSUE THREAD

**Issue by iluxa-com** [avast/gradle-docker-compose-plugin#175]
Sometimes it happens that some container fails to start. In this situation, the only way to debug is to set removeContainers = false or captureContainersOutput = true and wait for the problem to reproduce. Both options are not good since they lead to littering docker host or gradle logs.
It would be easier to troubleshoot such a situation having an option to fetch container logs on composeUp failure.

**Comment by augi** [comment]
There are more situations when it's useful to see logs of the containers, e.g. tests are failing.

My recommendation is to use `captureContainersOutputToFile` property to set a file where output of all containers will be written. Then you can include this file as your CI _artifact_ and so you could inspect it anytime and without littering the log.

**Comment by augi** [comment]
We could also make this change:
1. By default, set `captureContainersOutputToFile` to a file in `build` directory (now, default is `null`).
2. In case of `docker-compose up` failure, just print content of this file.

Would it be OK for your use-case, @iluxa-com?

**Comment by iluxa-com** [comment]
@augi it's easy to call `composerLogs` when some test fails, but you are right `captureContainersOutputToFile` works fine in my case, though searching through the multiple containers log is not much pleasant, especially when don't know which container had failed (docker-compose output is not much friendy: `ERROR: for my-service  Container "d62111ae7c9d" is unhealthy` where `d62111ae7c9d`  could be any dependee either depender.. no way to look up the id after composeDown), but looks like it is out of scope.
Thank you!

**Comment by augi** [comment]
You are welcome!

Btw. I've just released a new version (`0.8.12`) that has a new option: `captureContainersOutputToFiles`

It's directory where a new log file is created for each service. Hope it helps you little bit with debugging.

**Comment by iluxa-com** [comment]
Hi again! I've updated and it seems that `captureContainersOutputToFile` and `captureContainersOutputToFiles` don't work in case composeUp fails. Not sure it's broken by the new version, it's pretty possible that `captureContainersOutputToFile` didn't work in previous versions also in this case. Can't verify it - old logs already removed.
