### ISSUE TITLE
Support UDP ports

### ISSUE THREAD

**Issue by joshzamor** [avast/gradle-docker-compose-plugin#176]
It'd be useful to know which UDP ports are published to the host in `dockerCompose.servicesInfos`.

Even if there's something as simple as:
```groovy
def logUdpPort = dockerCompose.servicesInfos.log.firstContainer.udpPorts[514]
environment "myLogUdpPort", logUdpPort
```

That'd help me use rsyslog in a docker container with logback (which doesn't well support TCP).

**Comment by augi** [comment]
Released as `0.8.11`.
