### ISSUE TITLE
using startedServices fails on composePull

### ISSUE THREAD

**Issue by futchas** [avast/gradle-docker-compose-plugin#180]
I was trying to start multiple services inside a docker-compose file with `startedServices`.. Even just starting on service doesn't work.
`
dockerCompose {
    dockerComposeWorkingDirectory = 'docker/process-manager/clean-setups'
    useComposeFiles = ['docker-compose.yml']
//    startedServices = ['mysql-db', 'mailhog', 'samlidp', 'spm-dev']
    startedServices = ['mysql-db']
    captureContainersOutputToFile = 'docker.log'
`
I get following exception:
`
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':composePull'.
No signature of method: com.avast.gradle.dockercompose.ComposeExecutor.execute() is applicable for argument types: ([Ljava.lang.String;, java.lang.String) values: [[pull], mysql-db]
  Possible solutions: execute([Ljava.lang.String;)
`

**Comment by augi** [comment]
What plugin version do you use, please? And what Gradle version?

I've tried it locally and also improved the test (see [here](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/test/groovy/com/avast/gradle/dockercompose/DockerComposePluginTest.groovy#L223)) - both works for me :(

**Comment by futchas** [comment]
Sorry, my bad..I was using an older version. Updating to `0.8.12` helped and it works now
