### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by gargraman** [avast/gradle-docker-compose-plugin#181]
In my build.gradle how can I have different values for _dockerCompose_ extension?
e.g. I have two tasks cleanContainer and stopContainers where I dependsOn _composeDown_. I need to set property
**removeContainer = true** 
only for cleanContainer task and **removeContainer = false** for stopContainers

**Comment by augi** [comment]
You can have more `dockerCompose` extensions in one `build.gradle` using _nested configurations_ as described [here](https://github.com/avast/gradle-docker-compose-plugin#nested-configurations).

It's not possible to have different configuration values for tasks inside the same configuration, sorry.
