### ISSUE TITLE
Support for docker-compose pause and unpause

### ISSUE THREAD

**Issue by stewartbryson** [avast/gradle-docker-compose-plugin#185]
This would be useful for us. Thanks.

**Comment by stewartbryson** [comment]
FYI... I forked this repo and started to work on a PR, but there are already several unit tests that are failing. Is this a known issue, or something environmental?

**Comment by augi** [comment]
It must be semothing environmental - it works on Travis and even on my machine (Windows).
Which tests are failing?

**Comment by stewartbryson** [comment]
Nevermind... used `gradle` instead of `gradlew`. I have version 5 installed. Though it looks like you might have a little work to do to upgrade. ;-)

I'll carry-on. Thanks.

**Comment by augi** [comment]
I've just migrated the project to Gradle 5.2.1 and so all tests are working properly now.

**Comment by augi** [comment]
Hello, is your request still valid? Thanks!

**Comment by stewartbryson** [comment]
The request for Pause and Unpause is still a feature I would like to see. I didn't have time to work on it myself. If you think it's not relevant to a wider audience I understand if you close it.
