### ISSUE TITLE
feature request: print available services and endpoints 

### ISSUE THREAD

**Issue by gAmUssA** [avast/gradle-docker-compose-plugin#186]
Hello,

Is it possible to do similar things that `sbt-docker-compose` plugin has - print all available endpoints https://github.com/Tapad/sbt-docker-compose#instance-connection-information?

Thank you

**Comment by augi** [comment]
As the services are starting, the plugin already prints information about the exposed ports. So what you are suggesting is to print this table with summary of available services after all services are ready, right?

**Comment by gAmUssA** [comment]
@augi Yes, printing one table with all of the services (in contrast to tailing / searching log output) would extremely helpful

**Comment by augi** [comment]
`0.10.9` prints information like this:
```
+------------+----------------+-----------------+
| Name       | Container Port | Mapping         |
+------------+----------------+-----------------+
| postgres_1 | 5432           | localhost:32830 |
+------------+----------------+-----------------+
| redis_1    | 6379           | localhost:32831 |
+------------+----------------+-----------------+
| rabbit_1   | 15672          | localhost:32828 |
| rabbit_1   | 5672           | localhost:32829 |
+------------+----------------+-----------------+
```
