### ISSUE TITLE
composeDown not removing all containers

### ISSUE THREAD

**Issue by AnEmortalKid** [avast/gradle-docker-compose-plugin#187]
Tying the tasks with `dockerCompose.isRequiredBy(test)`

I notice that after `composeUp` runs, I have 13 containers:

`docker ps | wc -l # return 13`

When `composeDown` runs, only the last container is removed:

`docker ps | wc -l # returns 12`

From the `build --info` run:

composeUp (names obfuscated)
```
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency1 ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency1 ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency2 ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency2 ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency3 ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency3 ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency4     ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency5        ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency4     ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency5        ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency6      ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency6      ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency7_1       ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency7_1       ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency8_1  ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency9_1   ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency10_1   ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency12_1    ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency11_1 ...
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency8_1     ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency9_1      ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency10_1      ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency12_1       ... done
Starting 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__dependency11_1 ... done
Creating 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1           ...
Creating 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1           ... done

Will use localhost as host of myService
Waiting for myService_1 to become healthy (it's starting)
Waiting for myService_1 to become healthy (it's starting)
myService_1 health state reported as 'healthy' - continuing...
```

However when composeDown runs, only a single service is stopped:

```
> Task :my-service-test:composeDown
Stopping 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1 ... 
Stopping 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1 ... done
Removing 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1 ... 
Removing 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1 ... done
Going to remove 4940589b4c3564987b6ded9f8cef4ef2_my-service-test__myService_1

BUILD SUCCESSFUL in 2m 56s
7 actionable tasks: 2 executed, 5 up-to-date
```

Not entirely sure what I could have misconfigured:

```
dockerCompose {
    useComposeFiles = ['docker-compose.yml']
    startedServices = ['myservice']
}
```

**Comment by AnEmortalKid** [comment]
Hmm, I have a conjecture on this that I’ll try tomorrow. I wonder if it’s related to :

> startedServices = ['web'] // list of services to execute when calling 'docker-compose up' or 'docker-compose pull' (when not specified, all services are executed)

Since I only declare one, the plugin doesn’t know about the dependencies so it won’t shut those down. I’ll try it out with a second service there and see if that’s the case.

**Comment by augi** [comment]
Yes, the _problem_ is that the plugin just calls `docker-compose up web` and `docker-compose down web` (or `docker-compose rm` if `startedServices` is not empty).

The `up` command automatically starts also dependent services, unless `--no-deps` is specified ([docs](https://docs.docker.com/compose/reference/up/)).

On other hand, the `down` nor `rm` commands doesn't have option like `--no-deps` so it stops/removes just the mentioned services.

You have basically two choices:
1. Explicitly write also dependent services to `startedServices`
2. Add the dependent services names to the `downAdditionalArgs` option (at the end).

I would also happily accept a PR that would add a new option like `removeDependents` that would read dependencies of the `startedServices` and remove them during shutdown.

**Comment by AnEmortalKid** [comment]
Ah, that explains it. Usually on the command line I do `up web` and then `down`.

Would `downNoArgs` as a feature (basically calls down without args) be useful for everyone else?

If not I can do some research on gathering the dependencies of the services.

Thanks for the explanation!

**Comment by augi** [comment]
I wouldn't add a new task/option `downNoArgs`. But the proposed `removeDependents` would be great. The core will be IMHO parsing the output of `docker-compose config` command.

**Comment by AnEmortalKid** [comment]
Perfect, that gives me somewhere to start looking. Thank you!

I’ll try to implement this feature.

**Comment by augi** [comment]
The best place to write the new method would be probably [here](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L117).

If you don't want to dive into the codebase, I could implement this feature tomorrow.

**Comment by AnEmortalKid** [comment]
> If you don't want to dive into the codebase, I could implement this
feature tomorrow.

Ah, well if you beat me to it tomorrow that's fine :) I was gonna look at
it tomorrow since i have some free time!
