### ISSUE TITLE
captureContainerOutputToFiles does not capture dependent services

### ISSUE THREAD

**Issue by AnEmortalKid** [avast/gradle-docker-compose-plugin#190]
```
captureContainersOutputToFiles = '/path/to/directory' // sends output of all services to a dedicated log file in the directory specified, e.g. 'web.log' for service named 'log'
```

This might be related to the same underlying cause of #187 (plugin only knows about the services specified, so it only captures those logs)

Based on the doc on the readme, "all services", I assumed that implied also dependencies. If that's not the case, would a `captureDepenents` parameter be an appropriate/useful feature?

**Comment by augi** [comment]
Yes, it is the same kind of issue. If you choose just some services to start then it captures just these services (and not their dependencies).

The easiest solution to this issue would be to alter [getServiceNames()](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L118) method to return also dependent services.

Are you going to implement it? If no, I could implement it myself in couple of days.

**Comment by AnEmortalKid** [comment]
I'll implement it. Odd that when I did this: https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L139  I didn't include it in getServiceNames().

Probably because I was only doing `removeDependents`. Would overriding getServiceNames make it so dependents are removed even when `removeDependents` isn't specified? 

I think (at least to me), it makes sense that 'includeDependencies' be used to control both capturing container output / removing dependents.

**Comment by augi** [comment]
Agree that having just includeDependencies makes sense.
