### ISSUE TITLE
Allow plugin to read service `environment` variables

### ISSUE THREAD

**Issue by camhashemi** [avast/gradle-docker-compose-plugin#192]
In docker-compose it's common to specify the `environment` property for each service.

I would like to be able to read these variables from the dockerCompose plugin, is this possible? Currently it seems that I can only read from the dockerCompose's environment, and `servicesInfos` doesn't contain any environment information.

**Comment by augi** [comment]
Hi, the `servicesInfos` has [containerInfos](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ServiceInfo.groovy#L9) property - it's [ContainerInfo class](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ContainerInfo.groovy). And this class has [inspection property](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ContainerInfo.groovy#L14) that contains output of [docker inspect](https://docs.docker.com/engine/reference/commandline/inspect/) call.

So you can use something like `servicesInfos.firstContainer.inspection.Config.Env`. Please note that `Config.Env` from `docker inspect` is an array, e.g.
```yaml
"Env": [
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
```
