### ISSUE TITLE
Having stopContainers field set to false makes explicit calls to composeDown do nothing

### ISSUE THREAD

**Issue by ben-lei-gfm** [avast/gradle-docker-compose-plugin#202]
^title

For my use case, I make dockerCompose a requirement for bootRun (a Spring gradle task), and I don't necessarily want a failure in bootRun to bring all my containers down. But when I set `stopContainers` to false and later try to do a `./gradlew composeDown`, nothing happens.

I would expect an explicit `./gradlew composeDown` to be honored, regardless of the value of `stopContainers`.

**Comment by augi** [comment]
Hello, this behavior is described in the README. If `stopContainers` is set to `false` then `composeDown` does nothing. You can use `composeDownForced` task instead.

Unfortunately, it's not possible to check if the task was executed explicitly or as a dependency task, so we had to implement it in this way.
