### ISSUE TITLE
Consider using Gradle's configuration avoidance API 

### ISSUE THREAD

**Issue by celcius112** [avast/gradle-docker-compose-plugin#204]
Since last year there's a new Gradle API for registering tasks called the 'Configuration Avoidance API'. This API was incubating from Gradle 4.9 to Gradle 5.1 inclusively, but since 5.0 has been quite stable.

This API basically lets us defined tasks configuration lazily so that they are configured only if needed. While a tasks.create("myEagerTask") would always launch myEagerTask configuration, a tasks.register("myLazyTask) would configure it only if necessary. For instance launching the simple ./gradlew help would configure myEagerTask even though they are not related, but will not configure myLazyTask. Similarly, launching ./gradlew myLazyTask will configure myLazyTask and myEagerTask.

The docker-compose plugin configures all tasks eagerly. Their configurations does not take too much time (a ./gradlew help --scan shows they are configured in 0.17sec), but little by little, by using other plugins that aren't using this new API, we end up with several unnecessary tasks configured eagerly. It is also worth noting that the `create` API will one day be deprecated.

Since this API is only usable after Gradle 4.9, using it might bring breaking changes to the users. I don't see a minimum version recommendation for the docker-compose plugin, so before proposing a PR I wanted to discuss a bit about it. 
I see two solutions:
- Only configure lazily if the user is using Gradle >4.9
- Always configure lazily but setting the minimum Gradle version to 4.9. This would induce at least a minor version upgrade since the plugin is not officially released. This is my preferred  solution since Gradle 6 is coming pretty soon

**Comment by augi** [comment]
Hello and thank you for raising this issue!

I would also prefer to support just Gradle 4.9+. Gradle 3.x is not hopefully used at all, and Gradle 4.x users could migrate to 4.9 or higher without any problems.

I've just read [the documentation](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) and it's doable. My biggest concern is that tests would be probably need some major change, but it's doable as well.

I will try to prepare a PR in few days.
