### ISSUE TITLE
Feature Request: isRequiredBy accept a TaskProvider

### ISSUE THREAD

**Issue by durhammw** [avast/gradle-docker-compose-plugin#208]
I'd like to use Gradle's task avoidance API with my integration tests.  Today, this isn't possible because isRequiredBy takes a Task as a parameter instead of a TaskProvider.  Would it be possible to change isRequiredBy to accept a TaskProvider instead of a Task to address this?  Or add an overload of isRequiredBy to preserve backwards compatibility?

**Comment by augi** [comment]
Hello, thank you very much for your input! This absolutely makes sense and we will try to address this issue as soon as possible.

**Comment by durhammw** [comment]
Thanks for the change and the very quick response!
