### ISSUE TITLE
The plugin doesn't recreate containers when docker-compose.yml is changed and `stopContainers = false`

### ISSUE THREAD

**Issue by iirekm** [avast/gradle-docker-compose-plugin#213]
Such behavior is natural with all Gradle plugins, but unfortunately not this one :-(

For now have to use `docker rm -f $(docker ps -aq)` after every change in docker-compose.yml

**Comment by augi** [comment]
So if I understand your request correctly, you want to start the `docker-compose up` when `stopContainers` is set to `false`, even when cached services info is the same, but the `docker-compose.yml` has been changed. Is this correct?

Maybe the solution would be to alter the [getStateForCache()](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L118) method to also return output of `docker-compose config` command.

**Comment by iirekm** [comment]
Yes. For local testing stopContainers=false and yml change detection would
be nice.
docker-compose config on every build can be too slow. Maybe just comparing
old and new timestamp of yml file.

śr., 27 lis 2019, 11:08 użytkownik Michal Augustýn <notifications@github.com>
napisał:
