### ISSUE TITLE
buildAdditionalArgs fails when used with --build-arg ENV_NAME=local

### ISSUE THREAD

**Issue by bellini-ea** [avast/gradle-docker-compose-plugin#214]
Hello,
Fantastic plugin so thank you for creating it.
I may have found a potential issue when using buildAdditionalArgs option.  I am using gradle 5.6 and the kotlin dsl.

When using buildAdditionalArgs as follows, composeUp is successful
`buildAdditionalArgs = listOf("--force-rm")`

When using buildAdditionalArgs as follows, composeUp fails:
`buildAdditionalArgs = listOf("--build-arg ENV_NAME=local")`

The failure seems to think its due to wrong commandline args as the pipeline spits out out the docker usage
`Usage: build [options] [--build-arg key=val...] [SERVICE...]`

Interesting thing is if I add --info to the gradlew build and grab the command-line composeUp is wantoing to use and execute it manually, it works fine
` docker-compose --no-ansi -f ./docker/docker-compose.yml -p dda0414ea486d53c74adeb4c89ee4f32_blahblah_ build --build-arg ENV_NAME=local`

I can make it work if I do this which is probably a reasonable work around
`buildAdditionalArgs = listOf("--build-arg", "ENV_NAME=local")`

Seems to be only failing with --build-arg usage and my guess is that since it takes a secondary arg, something isn't happy with that.

Appreciate the help.

Cheers,
John

**Comment by augi** [comment]
Hello, and thank you for reporting!

Actually, the work around is the correct solution because technically `--build-arg` and `ENV_NAME=local` are two arguments.

I expect that specifying `listOf("--build-arg ENV_NAME=local")` causes command line like this: `docker-compose ... build "--build-arg ENV_NAME=local" ...`.

**Comment by amisiuryk** [comment]
Hello, 

Looks like the issue with **buildAdditionalArgs** is still there (latest 0.13.0 version) although 
`buildAdditionalArgs = listOf("--build-arg", "ENV_NAME=local")` is incorrect format and this one works:
`buildAdditionalArgs = ["--build-arg", "ENV_NAME=local"]`

I think it would be nice to update documentation with the description of this issue. 
And actually it looks like a bug as according to docker documentation
` --build-arg key=val     Set build-time variables for services.` it's one param. :)

**Comment by augi** [comment]
Hello, I'm not sure what issue are you describing :( The difference between `listOf("--build-arg", "ENV_NAME=local")` and `["--build-arg", "ENV_NAME=local"]` is that the first one is Kotlin syntax and the second one is Groovy syntax. So it depends on which language you use in your Gradle projects.
