### ISSUE TITLE
Different behaviour between docker-compose -d up and compose Up

### ISSUE THREAD

**Issue by bellini-ea** [avast/gradle-docker-compose-plugin#217]
I have 3 nested options for my use of your most excellent plugin:
```
createNested("dependencies").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("service1", "service2", "service3", "service4", "service5" )
    }

 createNested("kafka").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("kafka")
    }

 createNested("zookeeper").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("zookeeper")
    }
```
If I run the following, I get a failure:
1. gradlew  zookeeperComposeUp  (success) followed by
1. gradlew kafkaComposeUp (fails)

Failure is as follows:
```
> Task :app:kafkaComposeUp
kafka uses an image, skipping
Starting d286b40453ef35499ac4354c33ddd5d2_app_kafka_zookeeper_1 ...
Starting d286b40453ef35499ac4354c33ddd5d2_app_kafka_zookeeper_1 ... error

ERROR: for d286b40453ef35499ac4354c33ddd5d2_app_kafka_zookeeper_1  Cannot start service zookeeper: network f2acb0197b88e4190adb6668b3873727753beab5f67d6ca7ec9c8508cac51302 not found

ERROR: for zookeeper  Cannot start service zookeeper: network f2acb0197b88e4190adb6668b3873727753beab5f67d6ca7ec9c8508cac51302 not found
Encountered errors while bringing up the project.
```

If I run the following commands manually things start fine:
1. cd to app/docker
2. Run `docker-compose --file docker-compose-debug.yml up -d zookeeper`
3. Run `docker-compose --file docker-compose-debug.yml up -d kafka`

Seems like, potentially, the plugin is creating some other networks for each instance of calling `composeUp`?

**Comment by augi** [comment]
Hello and you for reporting this issue! ❤️ 

My bet is that a problem could be in the Docker Compose project name. It's specified using `-p` argument when calling all the `docker-compose` command. 

The project name is computer [in this method](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L110) and as you can see, it also works with name of the nested settings.

My recommendations:
1. Show us output of the successful `zookeeperComposeUp` command.
2. Try to specify the `projectName` of your settings manually, e.g. try to set it to the same value.

Please share output of these experiments with us, we could probably try to change the `generateProjectName` method implementation to support also your use-case, as you use the same `docker-compose.yml` file for all the nested settings.

Thanks!

**Comment by bellini-ea** [comment]
For #1, Attached is the result of zookeeperComposeUp.
[zookeeperComposeUp-user.txt](https://github.com/avast/gradle-docker-compose-plugin/files/3946971/zookeeperComposeUp-user.txt)

For #2, I set the project name as follows (here is the entire setups as well)

`dockerCompose {

    projectName = project.name
    useComposeFiles = listOf("./docker/docker-compose.yml")
    removeOrphans = true
    captureContainersOutput = true                                          
    captureContainersOutputToFiles = project.file("$buildDir/docker/")
    composeLogToFile = project.file("$buildDir/docker/compose.log")
    containerLogToDir = project.file("$buildDir/docker/containerlog.txt")
    buildAdditionalArgs = listOf("--build-arg", "ENV_NAME=containers")
    createNested("dependencies").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("poutine-redis", "mock-segmentation", "mock-segmentation-data", "mock-vts", "mock-vts-data" )
    }

    createNested("kafka").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("kafka")
    }

    createNested("zookeeper").apply {
        useComposeFiles = listOf("./docker/docker-compose-debug.yml")
        startedServices = listOf("zookeeper")
    }
}`

Log output attached.
[kafkaComposeUp-user.txt](https://github.com/avast/gradle-docker-compose-plugin/files/3946993/kafkaComposeUp-user.txt)

Note that last kafkaComposeUp also has another problem we are seeing which someone else has report

> Could not find method down() for arguments [] on provider(task kafkaComposeDownForced, class com.avast.gradle.dockercompose.tasks.ComposeDownForced) of type org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider_Decorated.

**Comment by augi** [comment]
Unfortunately, the `projectName` property is intentionally not inherited, so you have to repeat it all the nested settings. Please give it a try.

I don't see any suspicious in the logs. Are you using a custom Docker network?

> I will try to address the issue with the `down` method.

**Comment by bellini-ea** [comment]
Thanks.  Glad I posted the whole block then.  It works if I set the projectName = project.name in each nested block and the main block.  I think we can consider this a work around.  Might want to update the docs around projectName usage as I was looking for something like this but it didn't stand out to me.

Thanks for looking at the down method issue.

**Comment by augi** [comment]
Thanks! I've just updated the documentation of `projectName` property, and also published a new version of the plugin (`0.10.5`) with the invalid `down()` method call fixed.

**Comment by bellini-ea** [comment]
Thanks.  Oh and to answer a question you had for me, in our docker-compose files, we do specify a network where each service references the same one.

For example:
`kafka:
    image: bitnami/kafka:2
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT_TIMEOUT_MS=10000
    depends_on:
      - zookeeper
    networks:
      - blah_network
`

**Comment by augi** [comment]
Then it really requires to be created in the same Docker Compose project. Another option would be to declare the network as `external`, and ensure it has been created in a different way (e.g. call `docker network create` separately).
