### ISSUE TITLE
Running jib `:jibDockerBuild` before running docker-compose up

### ISSUE THREAD

**Issue by AdamMagaluk** [avast/gradle-docker-compose-plugin#219]
I'm looking for a way to kick off a `jibDockerBuild` task before `composeUp` is ran only in the cases where the cached services are not loaded.

Is this possible?

I can set up a dependant task on `composeUp` but this builds the image even if the cached services are used.  
```
composeUp.dependsOn jibDockerBuild
```

**Comment by augi** [comment]
Hello, I'm afraid that I don't know how to achieve this :(

**Comment by AdamMagaluk** [comment]
Thanks @augi for the quick reply.

I'll think on it a bit, not super familiar with gradle internals.

Maybe the using leveraging the [gradle task caching](https://docs.gradle.org/current/userguide/build_cache.html) to determine if the `composeUp` should ran instead of always running and changing the logic based on the state.

**Comment by augi** [comment]
Yes, I'm aware of up-to-date checks and Build Caching...but I still don't have any idea how to use it for this use case :(

**Comment by augi** [comment]
As I'm thinking about this, IMHO `composeUp.dependOn jibDockerBuild`  is correct solution. Then it's responsibility of the `jibDockerBuild` task to eventually perform no-op (if rebuild is not required).

**Comment by AdamMagaluk** [comment]
This seems a little backwards to me. (just my limited opinion though) I would expect `composeUp` to only run when build cache shows it as stale. Today it acts this way but through some internal caching that is not exposed through gradle.

**Comment by mosampaio** [comment]
+1

**Comment by augi** [comment]
The `composeUp` must be always executed because it verifies if the required are really running, and eventually starts them. And also `composeUp` must expose some information (about exported ports etc.).

I still believe the design of Gradle is OK, and so every task should be responsible for their own possible _no-op_. So it is responsibility of the `jibDockerBuild` tasks to do nothing if it is not required.

**Comment by NikolayMetchev** [comment]
I think this is related: https://github.com/GoogleContainerTools/jib/issues/1756
