### ISSUE TITLE
Setting to quickly fail if a container exits prematurely

### ISSUE THREAD

**Issue by gclayburg** [avast/gradle-docker-compose-plugin#223]
I have a container that I'm testing but sometimes during startup it fails and then the container quickly dies.  It never gets to the point where it listens on a TCP port.  This plugin will eventually fail too, but it seems like it needs to wait for a period of time before failing.  Is there a way to tell this plugin to fail quickly (and shut everything down) when it discovers that one container has started, but has stopped before listening on its configured TCP port?

**Comment by augi** [comment]
Seems to be good idea, thanks! A PR is welcome, or I will implement it soon myself.

**Comment by gclayburg** [comment]
oh ok.  I haven't looked at the code, but I could imagine doing this is similar to what you do now when checking for listening ports.
Also, I had some trouble changing the timeout value.  It seem to always use the value of 15 minutes.

This is the config I use:

```
dockerCompose {
    isRequiredBy(project.tasks.test)
    useComposeFiles = ['compose-smoke-synconsole.yml']
    waitForTcpPorts = true
    captureContainersOutput = true
    waitForHealthyStateTimeout = Duration.ofMinutes(5)
}
```

**Comment by augi** [comment]
Hello and sorry for the late response. I guess the problem is that your build is stuck on waiting for open ports - you have to use `waitForTcpPortsTimeout` settings. It wasn't documented, I've added it to the README right now.

**Comment by gclayburg** [comment]
Nice tip -  and it works!
