### ISSUE TITLE
If I service restarts on startup and it uses dynamic ports composeUp fails to detect new port

### ISSUE THREAD

**Issue by NikolayMetchev** [avast/gradle-docker-compose-plugin#229]
The composeUp task checks to see if a service has come up by talking to the ports defined for that service. However if a service fails to startup but has the restart option enabled, it will die and come back up quickly and get a new dynamic port. It appears as thought the docker-compose gradle plugin interrogates which port it should be checking once and then if the service restarts doesn't figure out the new port. The plugin should be checking which port to ping on every cycle in case the service has restarted.

**Comment by augi** [comment]
Thank you for reporting this issue! To be honest, I actually even haven't known that new ports are assigned after container restart.

**Comment by NikolayMetchev** [comment]
Thank you for the quick fix. When can I expect a new release of the plugin that includes this fix?

**Comment by augi** [comment]
It is actually released as `0.10.12`.
