### ISSUE TITLE
Configuring and pushing to repositories

### ISSUE THREAD

**Issue by gitsieg** [avast/gradle-docker-compose-plugin#241]
Hi! I have set up a docker-compose.yml that declares two containers with .env files. 
`composeUp` an `composeDown` works just fine locally. 

I want to push these containers to an azure container registry. How can I do this? 

After reading the readme, the solution was not obvious to me. Can someone please shed some light on this?

**Comment by augi** [comment]
Hello, the provided `composePush` command just executes the `docker-compose push` so please discuss this with [the official Docker Compose documentation](https://docs.docker.com/compose/reference/push/).
