### ISSUE TITLE
Use custom DOCKER_CONFIG directory

### ISSUE THREAD

**Issue by simongarciam** [avast/gradle-docker-compose-plugin#244]
I am trying to specify a custom DOCKER_CONFIG environment variable when running gradle with the plugin to use a custom docker config directory

When running DOCKER_CONFIG=custom ./gradlew composeUp It does not seem to pick this up.

Running the same thing with docker-compose directly works for me.
ie. DOCKER_CONFIG=custom docker-compose up

I want to have a custom config.json to store the different credential helpers for private registries in my repo to use the amazon-ecr-credential-helper

Am I doing this wrong?

**Comment by simongarciam** [comment]
I was able to figure this out.  The path I was passing to the env variable needs to be an absolute path for this to work.

**Comment by augi** [comment]
Hello, yes, all the environment variables of the current process are propagated to the executed commands so it should work as expected.
