### ISSUE TITLE
Period between probing TCP ports

### ISSUE THREAD

**Issue by T00fy** [avast/gradle-docker-compose-plugin#246]
Hi, is there a way to increase the time between each TCP port probe? One of our containers takes a long time to start and the console is flooded with messages.

I could make a PR if this is something the plugin does not currently support.

**Comment by augi** [comment]
Hello, the configs you are looking for are `waitAfterTcpProbeFailure` and `waitAfterHealthyStateProbeFailure`. I'm going to document them in README.
