### ISSUE TITLE
"docker stack deploy" for enabling resources management in compose version 3

### ISSUE THREAD

**Issue by boehlke** [avast/gradle-docker-compose-plugin#249]
Hi,
thank you for maintaining this useful gradle plugin, we happily use the plugin for over a year now.

When trying to upgrade to a new docker-compose configuration version 3.8, we migrated mem_limit to deply->resources->limits->memory which results in a message:

`Some services (...) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.`

Are you planning to support deploying with "docker stack deploy"? Would a pull request be welcome? Thank you!

**Comment by augi** [comment]
Hello, thank you for reporting this issue. Unfortunately, this error message comes directly from the `docker-compose`, not from the plugin, so I'm afraid that we are not able to fix this.

This plugin was created to simplify mainly integration testing so we don't plan to add support for `docker stack deploy`. But you can briefly describe what do you want to achieve and how do you want to implement that. If it fits the plugin design, PR would be welcomed 👍

**Comment by boehlke** [comment]
Thank you @augi
I will try to find a way how `docker stack deploy`  might fit into the plugin!
