### ISSUE TITLE
TaskProvider overload for isRequiredBy should be covariant with Task

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [avast/gradle-docker-compose-plugin#251]
The TaskProvider overload of `isRequiredBy` accepts a `TaskProvider<Task>`. When using the Kotlin Gradle DSL, this means that the following (recommended) configuration method will not work:
```kotlin
dockerCompose.isRequiredBy(tasks.test)
```
The expected behavior is that isRequiredBy should accept `tasks.test`, whose type is `TaskProvider<Test>`. The compiler however does not recognize `TaskProvider<Test>` as a subtype of `TaskProvider<Task>`, and thus produces the following error:
```
None of the following functions can be called with the arguments supplied: 
public open fun isRequiredBy(p0: Task!): Unit defined in com.avast.gradle.dockercompose.ComposeExtension
public open fun isRequiredBy(p0: TaskProvider<Task!>!): Unit defined in com.avast.gradle.dockercompose.ComposeExtension
```

There are two workarounds:
```kotlin
// 1. with task configuration avoidance, warns about unchecked cast
dockerCompose.isRequiredBy(tasks.test as TaskProvider<Test>)

// 2. without task configuration avoidance
dockerCompose.isRequiredBy(tasks.test.get())
```

I guess Groovy being more lax about types masks the problem when using Groovy buildscripts.

If the Java solution also applies in Groovy, I believe the solution would be to change the method signature to `void isRequiredBy(TaskProvider<? extends Task> taskProvider)`

**Comment by augi** [comment]
Hello, thank you very much for reporting this issue! I wasn't aware of this because I'm still using Groovy for Gradle scripts. The proposed update of `isRequiredBy` signature is contained in the `0.13.2` release.

**Comment by JamiesWhiteShirt** [comment]
Thanks for the quick fix. I can confirm that 0.13.2 resolved the issue.

**Comment by augi** [comment]
That's great news! 🎉
