### ISSUE TITLE
Log an error/warning when composeDown is executed when stopContainers = false

### ISSUE THREAD

**Issue by jvwilge** [avast/gradle-docker-compose-plugin#252]
I'm using the init script referenced in the readme: https://github.com/avast/gradle-docker-compose-plugin/blob/master/init.gradle to set `stopContainers` to `false`(which really speeds up my development cycle btw 👍 ).

When I do a `./gradlew composeDown` it completes without warnings/errors, but this won't stop the containers. This behaviour is expected but it has bitten me a few times and I can imagine I'm not the only one.

Is it possible to print a warning/error like :
> You're trying to stop the containers, but stopContainers is set to false. Please use composeDownForced

I think this will save us some debug-time

**Comment by augi** [comment]
Hello, that's great idea! I've just added the logging, as `lifecycle`. The change will be released very soon.
