### ISSUE TITLE
tcp port check doesn't work with bind IP specified

### ISSUE THREAD

**Issue by rpanak-generalbytes** [avast/gradle-docker-compose-plugin#256]
Using gateway address for tcp port check doesn't make sense IMO. It works if no bind IP is specified for the port mapping (by accident rather than by design). In such a case, the docker-proxy process binds on all available interfaces (including the one used for the gateway) and one can connect to the gateway on the given port successfully.

The problem can be reproduces easily with a port mapping "127.0.0.1:8080:8080". Unlike the mapping "8080:8080", docker-proxy only binds to 127.0.0.1, but the tcp port check never succeeds because it checks the gateway IP address. I'd suggest taking the bind IP from the port mapping into account. Alternatively, container port can be checked instead of host port. In such a case, the container IP address could be used.

For remote docker hosts (DOCKER_HOST=...) this is broken even further as for some bind IPs (like the mentioned localhost) there might be no way to test this from outside of the docker host.

**Comment by briceburg** [comment]
IMO we should be using `host.docker.internal` instead of the gateway address if running gradle from within a container (that has bound to the hosts docker socket)
