### ISSUE TITLE
Containers do not join common Network

### ISSUE THREAD

**Issue by realulim** [avast/gradle-docker-compose-plugin#262]
I have a docker-compose.yml file with a database and an application that are connected together via a common network like so:

```
services:
  db:
    [...]
    networks:
      - mynet
  app:
    [...]
    networks:
      - mynet
networks:
  mynet:
```
If I run that via docker-compose, everything works as expected. Both containers join the common network and the app can connect to the db. However, when run via `gradlew composeUp` things are different: two seperate networks are created instead of just one and hence no communication is possible between the containers. I have verified with `docker inspect` that indeed each container is in its own network.
This is the output of `docker network ls`:
```
NETWORK ID          NAME                                               DRIVER              SCOPE
e76c0ff1cc38        1d023e2c920237d9d3a641beafe879c1_subproject1__mynet      bridge              local
21d8bbe74518        114d32d969b22d50be373fdfaa9372a8_rootproject__mynet   bridge              local
```
subproject1 is the name of the Gradle subproject for the app, whereas rootproject is the name of the parent Gradle project as per settings.gradle. It appears that the network names have been generated from Gradle project / subproject names. If I run my docker-compose.yml file via docker-compose directly, then the output of `docker network ls` is like this:
```
NETWORK ID          NAME                DRIVER              SCOPE
6453132f4c80        rootproject_mynet             bridge              local
```
As expected, just one network and both containers are in it.

**Comment by realulim** [comment]
The issue may have to do with me having defined seperate `docker-compose { ... }` configuration blocks in the two subprojects for db and app. For instance, in the build.gradle of the db subproject:
```
dockerCompose {
    environment.put 'COMPOSE_DOCKER_CLI_BUILD', '1'
    startedServices = ['db']
    ...
}
```
Whereas in the app subproject:
```
dockerCompose {
    environment.put 'COMPOSE_DOCKER_CLI_BUILD', '1'
    startedServices = ['app']
    ...
}
```
This is so I could have different configurations for building the images. If I add a `projectName = "MyProj"` to both configurations, then only one network is created. However, I am then getting a different error upon `gradlew composeUp`:

```
Creating network "114d32d969b22d50be373fdfaa9372a8_jstage-cms__cmsnet" with the default driver
Creating app ... 
Creating db  ... 
Creating app ... done
Creating db  ... done
Will use 172.30.0.1 (network 114d32d969b22d50be373fdfaa9372a8_rootproj__mynet) as host of db
Will use 172.30.0.1 (network 114d32d969b22d50be373fdfaa9372a8_rootproj__mynet) as host of app
Probing TCP socket on 172.30.0.1:3307 of 'db'
TCP socket on 172.30.0.1:3307 of 'db' is ready
Probing TCP socket on 172.30.0.1:8091 of 'app'
Waiting for TCP socket on 172.30.0.1:8091 of 'app' (Connection refused (Connection refused))
Will use 172.30.0.1 (network 114d32d969b22d50be373fdfaa9372a8_rootproj__mynet) as host of app
[... retry ...]
TCP socket on 172.30.0.1:8091 of 'app' is ready
+---------+----------------+-----------------+
| Name    | Container Port | Mapping         |
+---------+----------------+-----------------+
|      db  | 3306           | 172.30.0.1:3307 |
+---------+----------------+-----------------+
|     app | 8091           | 172.30.0.1:8091 |
+---------+----------------+-----------------+

> Task :app:composeUp FAILED
Native build is an experimental feature and could change at any time
Creating network "MyProj_mynet" with the default driver
Creating app ... 
Creating app ... error

ERROR: for app  Cannot create container for service app: Conflict. The container name "/app" is already in use by container "06c0fe1950c0c5f1b1289f653584535b2fc9e84c7af85b0bf2f5cdc7b7936126". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by augi** [comment]
Hello,

the difference is that you executed manually `docker-compose up` just once, while if you specify two `dockerCompose` blocks in Gradle, the `docker-compose up` is executed twice - first, it starts the `db` service, and then the `app` service.

The names of objects created by `docker-compose` are driven by `projectName` (this is feature of Docker Compose). If it is not specified, Docker Compose automatically uses directory name. This Gradle plugin uses slightly different algorithm to specify `projectName` (that is also based on directory location) but you can override this with the `projectName` option (as you did).

The log you showed is probably related to a `dockerCompose` block that doesn't specify the `startedServices` as we can see both services are being started.

Hope the information I provided are sufficient to implement your use-case successfully.

**Comment by realulim** [comment]
Yes, I do want to start composeUp twice, first run the DB service only and the second run only the App service. Basically, the equivalent to "docker-compose up db; docker-compose up app" - how can I do that if not the way I have tried?

**Comment by augi** [comment]
According to the log, it looks like you are starting both `app` and `db` services, and so it failed on the conflict because the `app` container already existed. Don't you have a misconfiguration of the plugin?

**Comment by realulim** [comment]
The weird thing is, it looks like both services are started twice, but:

a) I don't understand why the services are started twice, because I configured the "startedServices" parameters as shown above. That way for each invocation only one service should be started.
b) The two starts happen only when I define the projectName parameter. If I don't define that, each service is only started once (but in different networks).

**Comment by realulim** [comment]
Ok, the problem seems to be that I have a multi project build in Gradle. There's the root project, which is just a shell, and the two subprojects db and app. No matter where I put the `dockerCompose {...}` block (in the root project's `build.gradle` or one each in the build files of the subprojects), the execution order is always like this:
```
:composeUp
:app:composeUp
:db:composeUp
```
I would assume that my original problem with containers starting in their own network is also a result of composeUp being run multiple times. The multi project build seems to generally be problematic in the context of docker-compose tooling: https://github.com/s4s0l/bootcker-gradle-plugin

**Comment by realulim** [comment]
Ok, the way to use this plugin in multi project builds is to never call the "composeUp" or "composeBuild" tasks, but rather always address each subproject seperately:
```
gradlew db:composeUp
gradlew app:composeUp
```
For this to work, there needs to be a `dockerCompose {...}` block in each of the subproject's build files, where the services are restricted to just the one service of the subproject, plus the project name needs to be the same or else the containers won't be started in the same network:
```
dockerCompose {
    projectName = "myApp"
    startedServices = ['db']
}
dockerCompose {
    projectName = "myApp"
    startedServices = ['app']
}
```

**Comment by augi** [comment]
Exactly, this is the way how it should work.
