### ISSUE TITLE
`isRequiredBy` resolves dependencies at configuration time

### ISSUE THREAD

**Issue by jdai8** [avast/gradle-docker-compose-plugin#263]
[This call](https://github.com/avast/gradle-docker-compose-plugin/blob/0.13.3/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L188) to [`TaskDependency.getDependencies()`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskDependency.html#getDependencies-org.gradle.api.Task-)causes dependencies to be resolved at configuration time. This slows down builds and prevents other plugins from mutating the configuration (e.g. adding attributes) before it gets resolved.

For example:
```
dockerCompose {
  isRequiredBy(run)
}
```
will resolve the `runtimeClasspath` configuration.

## Potential solution
The intention is to run the up task after things have finished compiling right? 

Simply wrapping in a `taskGraph.whenReady` might work:
```
task.dependsOn upTask
task.finalizedBy downTask
project.taskGraph.whenReady {
    task.getTaskDependencies().getDependencies(task)
                .findAll { Task.class.isAssignableFrom(it.class) && ((Task) it).name.toLowerCase().contains('classes') }
                .each { dep ->
                    if (fromConfigure) {
                        upTask.get().shouldRunAfter dep
                    } else {
                        upTask.configure { it.shouldRunAfter dep }
                    }
       }
}
```

I'm happy to put up a PR if this seems like the right solution.

**Comment by augi** [comment]
Hello, thank you for reporting this issue! Feel free to prepare a PR containing this improvement. I'm just not sure if it is possible to use `shouldRunAfter` from `whenReady` (just because I don't have experience with it). If it works, then perfect 👍
