### ISSUE TITLE
Add support for COMPOSE_HTTP_TIMEOUT

### ISSUE THREAD

**Issue by NikolayMetchev** [avast/gradle-docker-compose-plugin#265]
We are occasionally getting the error below. Is it possible to add support for the environment variable COMPOSE_HTTP_TIMEOUT to help combat this:

ERROR: for swift  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by augi** [comment]
Hello, this plugin has `environment` option that allows to set any environment variable to be used when calling `docker-compose` commands. So my recommendation is to use this way to configure this timeout.

It is IMHO better solution than introducing a specific option to the plugin, e.g. we don't have to deal with default values.
