### ISSUE TITLE
Unknown Property 'Duration'

### ISSUE THREAD

**Issue by realulim** [avast/gradle-docker-compose-plugin#269]
I have a build.gradle with something like:
```
dockerCompose {
    [...]
    waitForTcpPortsTimeout = Duration.ofMinutes(1)
}
```
I am getting this error message with Gradle 4.9:
`Could not get unknown property 'Duration' for object of type com.avast.gradle.dockercompose.ComposeExtension`

The error message disappears with Gradle 6.5 (haven't tested other versions), but since 4.9 is mentioned as the minimum version supported, I thought to report this. Perhaps the docs have to be changed?

In any event, since I cannot upgrade my Gradle project easily to 5 or more, is there a way to specify the timeout that doesn't rely on a newer Gradle version?

**Comment by augi** [comment]
Hello, thanks for your report! We forget to use full name (`java.time.Duration`) in few places in the documentation.

**Comment by realulim** [comment]
Many thanks, using the fully qualified path works with Gradle 4.9. So I suppose higher versions of Gradle have the java.time package automatically on the classpath.
