### ISSUE TITLE
Maven Central publishing

### ISSUE THREAD

**Issue by bwaldvogel** [avast/gradle-docker-compose-plugin#281]
Since [JCenter will shutdown until May 1st 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), is there any plan to publish the artifacts to Maven Central?

**Comment by augi** [comment]
HI, yes, I would like to publish the artifacts to Maven Central, and also use GitHub Actions instead of TravisCI. I will do it hopefully until end of February.

**Comment by bwaldvogel** [comment]
Thanks for the update!

**Comment by augi** [comment]
Version `0.14.2` is published to Maven Central 🎉

**Comment by bwaldvogel** [comment]
Thanks!
