### ISSUE TITLE
"--no-ansi option is deprecated and will be removed in future versions" - warning printed on console

### ISSUE THREAD

**Issue by tkrah** [avast/gradle-docker-compose-plugin#287]
Starting or stopping containers with the plugin will always result in this warning printed:

`
--no-ansi option is deprecated and will be removed in future versions`

I did however not specify that "--no-ansi" argument in my configuration, so it must be something the plugin itself does append - I see that with the "--info" output, however I don't know how to get rid of that usage.

Please remove the usage of that option.

**Comment by augi** [comment]
Hello, thank you for your report! This issue was addressed in the `0.14.1` so please just update to the latest version.

https://github.com/avast/gradle-docker-compose-plugin/releases/tag/0.14.1

If the problem persists, feel free to reopen this issue.

**Comment by tkrah** [comment]
Thx,sorry for the noise - searched the issue tracker and did not find one though - should have tested the latest release, was still on 0.14.0. It is gone now, thanks.
