### ISSUE TITLE
composeUp fails on v2-beta when defining a working directory

### ISSUE THREAD

**Issue by LaurensLeeuwis** [avast/gradle-docker-compose-plugin#310]
I've installed the latest Docker Desktop on my Mac, which comes with a new version of `docker-compose`:

```shell
$ docker-compose version --short
v2.0.0-beta.6
```

When using this version of `docker-compose` it gives me problems when starting `composeUp` when I defined a `dockerComposeWorkingDirectory`. Here is my setup:

`./build.gradle`:

```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.avast.gradle:gradle-docker-compose-plugin:0.14.5"
    }
}

apply plugin: 'docker-compose'
dockerCompose {
    useComposeFiles = ['my-docker-compose-file.yml']
    dockerComposeWorkingDirectory = 'myfolder'
}
```

`./myfolder/my-docker-file.yml`:

```yml
version: "3.7"
services:
  aservice:
    image: nginx
    ports:
      - 81:80
```

Starting up:

```shell
$ ./gradlew composeUp
> Task :composeUp
Network 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__default  Creating
Network 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__default  Created
Container 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__aservice_1  Creating
Container 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__aservice_1  Created
Container 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__aservice_1  Starting
Container 540a71231b50b53dd1e908af1e6d09f3_avast-docker-compose-plugin-reproduction__aservice_1  Started

> Task :composeUp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeUp'.
> Custom Docker Compose file not found: /Users/myuser/code/avast-docker-compose-plugin-reproduction/my-docker-compose-file.yml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed
```

As you can see it first starts the containers (so it can find the yaml), but then it complains that it can't find it.

I had a look in the code, and I think it there are two problems around [line 150 in `ComposeExecutor.groovy`](https://github.com/avast/gradle-docker-compose-plugin/blob/03e12dfafe322762782347374e1aa56c060071e4/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L150):

1. The version of `docker-compose` can't be parsed. An older version gave `1.29.1`, the new one gives `v2.0.0-beta.6`, which has quite a different format
2. Because of that it won't run `config --services`, but goes to the fallback path. That doesn't take the `dockerComposeWorkingDirectory` into account

As a workaround I added `startedServices = ['aservice']` to my configuration, and then it indeed works because it's going into another branch of the same function.

**Comment by augi** [comment]
Hello, thank you very much for reporting this issue! And also for the detailed investigation you did! 👍

I will prepare the fix ASAP, but it could take few days, during these lazy summer days 😎

**Comment by augi** [comment]
The fixes are released in `0.14.6`. Thank you again for your report! 👍

**Comment by LaurensLeeuwis** [comment]
Thanks for the new (and quick) release!

I'm afraid it doesn't work anymore on Gradle 5.6. It seems to need 7.1 or higher.

**Comment by augi** [comment]
Yes, sorry for the inconvenience 😔 I will try to resolve this issue ASAP, please watch #312 :pray:
