### ISSUE TITLE
composeUp fails after upgrading from 0.14.3 -> 0.14.4

### ISSUE THREAD

**Issue by jvwilge** [avast/gradle-docker-compose-plugin#312]
Hi we had an issue when upgrading from 0.14.3 to 0.14.4 when running `./gradlew composeUp` :
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeUp'.
> Receiver class com.avast.gradle.dockercompose.ServiceInfo does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
```

I did a diff on both tags and saw some changes in the Gradle version, so I decided to upgrade to 7.1.1 and the problem was gone.

We use version 6.8.3 of Gradle (and I also tried with 6.8.2 and 6.9).

For us upgrading Gradle resolves the issue, but other people might not be able to upgrade or maybe there's an issue with the plugin code.

Also this issue might save other people some time (when running into the same problem).

**Comment by augi** [comment]
Hello, thank you for reporting this issue! It looks like the problem is that Gradle 6 and Gradle 7 use different major version of Groovy. I will try to downgrade the Gradle version to the latest 6.x and test it in Gradle 7.x based projects.

I will also try to add cross-version tests.

**Comment by augi** [comment]
[0.14.8](https://github.com/avast/gradle-docker-compose-plugin/releases/tag/0.14.8) 🎉
