### ISSUE TITLE
dockerComposeWorkingDirectory is not working

### ISSUE THREAD

**Issue by rkavitha** [avast/gradle-docker-compose-plugin#314]
I am using:

plugins {
    id 'com.avast.gradle.docker-compose' version '0.14.9' // https://github.com/avast/gradle-docker-compose-plugin , https://bmuschko.com/blog/gradle-docker-compose/
}

gradle-7.1.1

Error:

Cannot set the value of extension 'dockerCompose' property 'dockerComposeWorkingDirectory' of type org.gradle.api.file.Directory using an instance of type java.lang.String.

**Comment by augi** [comment]
Hello, thank you for reporting this issue.

Could you please share how do you set the property? Maybe you could try something like `project.file` to convert `String`, as the error message says.

**Comment by rkavitha** [comment]
This worked:


dockerComposeWorkingDirectory =  project.getLayout().getProjectDirectory().dir("relativePath")

Thank you,
Kavitha
________________________________

**Comment by augi** [comment]
Yes, this is correct 👍 I forget to update documentation, I will do it ASAP. Sorry for the inconvenience :pray:

**Comment by augi** [comment]
Also please note that `DirectoryProperty` can be set from regular `java.io.file` so you could also use `project.file('relativePath')`. I've just added this information to README.
