### ISSUE TITLE
Kotlin nested example missing

### ISSUE THREAD

**Issue by FrogDevelopper** [avast/gradle-docker-compose-plugin#316]
There is an example of how create the nested ComposeSettings for Groovy but not for Kotlin
(code present on [PR#172 - Add kotlin example of nested configuration to readme](https://github.com/avast/gradle-docker-compose-plugin/pull/172))

**Comment by augi** [comment]
Hello, thank you for reporting this. This issue is already being solved in #315 - I have no experience with Kotlin DSL so we are waiting for someone who is able to provide such an example.
