### ISSUE TITLE
compseUp no longer waiting for setvice to start?

### ISSUE THREAD

**Issue by Arc-E-Tect** [avast/gradle-docker-compose-plugin#323]
Hi,

been using the plugin for a while now, all worked fine until recently.

Now when I do a composeUp as part of a regular build cycle (`gradlew build`) and triggered by `dockerCompose.isRequiredBy(...)` it fails stating that a service could not be found. (`no such service: ...`).

Running a regular `docker-compose up` of `docker compose up` from the command line works perfect. In Docker Desktop I do see the conainer popping up.

Problem is on Windows 10 , Gradle 7.2,  Docker Enginer v20.10.8, docker-compose v2.0.0-rc.3

Any idea what's causing this? Something I need to configure because of a Docker Update?

Thanks in advance

**Comment by augi** [comment]
Hello, could you please share full error message (or better, full log) and docker-compose.yml file? 🙏

**Comment by Arc-E-Tect** [comment]
Hi,
Thanks for the quick response. I created an extremely minimalist project that shows the exact same behavior: [docker-compose-experiment](https://github.com/Arc-E-Tect/docker-compose-experiment). It is a public repository. 

The README.md explains what to do, with the output I get as well.

**Comment by KroArtem** [comment]
I didn't dive into the issue a lot but since compose version 3 docker-compose doesn't wait for services to start, you may check more info [here](https://docs.docker.com/compose/startup-order/)

**Comment by augi** [comment]
Hello @Arc-E-Tect , from the information provided, it looks like you are running experimental version of Docker Compose and so this is root of your issue: https://docs.docker.com/compose/cli-command/

So you should be able to _downgrade_ to the latest stable version by executing `docker-compose disable-v2`.

Debugging why it fails on Docker Compose v2 would require more time that I'm not able to allocate right now 😢 

If support of Docker Compose v2 is critical for someone, any PR is welcome 🙏

**Comment by Arc-E-Tect** [comment]
Hi @augi 
That was the problem and you provided the solution. I have no need for the v2 of Docker Compose.

Thanks a lot.

**Comment by augi** [comment]
@niloc132 Thank you for digging into this! Yes, executing `docker-compose ps` looks like a way. Also, we could try to retry the current command until `no such service` message disappear. But I don't like `string`-based `if`s so I would prefer what you are suggesting. We could also check if output of `docker-compose ps` contains all the expected services 🤔 But feel free to start with non-emptiness checking.

**Comment by joshua-paypay** [comment]
Hi I am encountering this issue. Can we re-open this issue? Thanks

**Comment by joshua-paypay** [comment]
@niloc132 
I've made a similar fix https://github.com/avast/gradle-docker-compose-plugin/pull/363
Can you help check if the logic is identical to what you want?

@augi Can you help me on this PR so I can continue? Thanks.

**Comment by joshua-paypay** [comment]
I found my issue is not related to this one. Sorry.

**Comment by niloc132** [comment]
Note that v2 has GA's, and so v1 is EOL'd, will be removed in less than a year. 

https://github.com/docker/roadmap/issues/257
