### ISSUE TITLE
Release 0.14.9 doesn't support strings for removeImages option

### ISSUE THREAD

**Issue by rherrick** [avast/gradle-docker-compose-plugin#324]
I just updated from 0.14.0 to 0.14.9, which broke the build. I have this in my configuration (some lines removed for clarity):

```
dockerCompose {
    removeImages = "All"
}
```

I tried to upgrade my Gradle wrapper and got an error:

```
# gradle wrapper --distribution-type=all --warning-mode=all

> Configure project :
Compose build args: []

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/username/Development/tool-docker-compose/build.gradle' line: 111

* What went wrong:
A problem occurred evaluating root project 'xnat-docker-compose'.
> Cannot set the value of extension 'dockerCompose' property 'removeImages' of type com.avast.gradle.dockercompose.RemoveImages using an instance of type java.lang.String.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

If I revert to 0.14.8, my build configuration works. For 0.14.9, I have to add this:

```
import com.avast.gradle.dockercompose.RemoveImages

...

dockerCompose {
    removeImages = RemoveImages.All
}
```

I'd prefer to be able to use a string, just so I don't have to add the `import` statement, but staying with the `RemoveImages` enum requires a documentation change to note that setting `removeImages` requires the `import` and setting the configuration to one of the enum values.

**Comment by augi** [comment]
Sorry for the inconvenience and the troubles caused 😢 

Unfortunately, the exact value of that enum is required, e.g. `com.avast.gradle.dockercompose.RemoveImages.All` (so you don't have to use `import`.

The example will be updated.

Thank you for reporting this! 👍
