### ISSUE TITLE
Use .env file

### ISSUE THREAD

**Issue by snagiel** [avast/gradle-docker-compose-plugin#325]
As a substitute for `environment.put`, it would be great to expose an attribute (e.g. `env.file`) that points to an external *.env file, which could then be read for variable injection. 

This would be preferred since this is the standard way of doing so with docker-compose (https://docs.docker.com/compose/environment-variables/), and could take advantage of such files already being used in different environments (e.g. local/dev, CI/staging, etc.)

**Comment by augi** [comment]
Hello, you could add [--env-file option](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option) to `composeAdditionalArgs`.

We are not going to introduce a new attribute for every Docker Compose option, we believe this is more flexible.
