### ISSUE TITLE
'composeBuild' task doesn't work, when additional args are provided

### ISSUE THREAD

**Issue by uzhauniak** [avast/gradle-docker-compose-plugin#327]
**Description:** when starting 'composeBuild' task via terminal with command `gradle composeBuild`, no build is performed and `docker-compose build` help is printed out instead.

**Prerequisites:**

- Gradle - Version 7.1.1.
- build.gradle configuration:      
> dockerCompose {
>           useComposeFiles = ['docker/docker-compose.yml']
>           buildAdditionalArgs = ['--build-arg 1=2']
>       }

Gradle execution logs
[gradle_logs.txt](https://github.com/avast/gradle-docker-compose-plugin/files/7475439/gradle_logs.txt)

**Comment by augi** [comment]
Hello, you have to specify the arguments as separate parameters, like `buildAdditionalArgs = ['--build-arg', '1=2']`

If this doesn't help, please don't hesitate to reopen this issue.

**Comment by uzhauniak** [comment]
Hi, thanks for help. It worked!
