### ISSUE TITLE
composeDown: should be just down

### ISSUE THREAD

**Issue by dreamershl** [avast/gradle-docker-compose-plugin#329]
"startedServices" isn't just affect the composeUp task. composeDown task will also use it for "down" or "rm". It is misleading. 

When up, docker-compose will also start the dependent services. So should not just "rm" "startedServices" when composeDown.

**Comment by augi** [comment]
Hello, we don't want to rename `startedServices` now as it would break backward compatibility.

Please note the the `down` task doesn't use the `startedServices` value (the code [here](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeDownForced.groovy#L32)), it uses the value computed in [this method](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L151) that includes also dependent services.

**Comment by dreamershl** [comment]
In my current project, the "startedService" will cause the dependent services keep running.

I believe. the issue is caused by the line 

Pls refer to line 27~35. If the "startedService" is empty, the "down" will be called and that will clear the running dependents properly. Otherwise, only specified services volume will be removed. 

https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeDownForced.groovy#L27-L35

That is why I would like to suggest to follow docker-compose down semantic.

**Comment by augi** [comment]
IMHO the implementation follows the `docker-compose down` semantics because it tries to find also the dependent services and stop them as well. As I wrote, [the code to get services to stop is here](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L151)

So as you can see, also `includeDependencies` must be set to `true`. Maybe this is what you are missing in your configuration.

**Comment by dreamershl** [comment]
I just tested out the option "includeDependencies" as the following

``` groovy
dockerCompose {
    projectName = "integration-test"
    useComposeFiles = ["docker-compose.yml", "../docker/kafka-compose.yml"]
//    includeDependencies = true
//    startedServices = ["kafka"]
}
```

1. without startedServices, the composeDown task is able to clear all the running dependencies, such as zookeeper
2. with the startedServices & includeDependencies, composeDown task will only stop and remove service kafka and leave the zookeeper running.

will try to figure out why the dependent services are not included.

**Comment by augi** [comment]
OK, thank you! The plugin computes dependencies from `docker-compose config` output so maybe it has been changed and the plugin is not able to parse it anymore.

[This is the class](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeConfigParser.groovy) responsible for the output parsing.

**Comment by dreamershl** [comment]
I can't reproduce this issue any more. have also try out the unit test with the docker-compose version 3. it works perfectly. 

> includeDependencies must be set to true
