### ISSUE TITLE
Environment variables can't be properly exposed for docker-compose v2

### ISSUE THREAD

**Issue by chao-chang-paypay** [avast/gradle-docker-compose-plugin#332]
currently we are assuming the service instance name would suffix with `_1`, `_2`,  this is true for docker-compose v1, but for v2, the name suffix would be `-1`, `-2` , thus breaking the assumption, as the result, the environment variables would not be  able to be exposed properly.

Reference:
https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L272-L278

**Comment by augi** [comment]
Thank you for reporting this, it is fixed in `0.14.10`. But please note that there is no full support for v2 yet :(
