### ISSUE TITLE
Compose up issues with longer project names

### ISSUE THREAD

**Issue by wiiitek** [avast/gradle-docker-compose-plugin#338]
I have observed that there are some issues regarding long (with lot of dashes) project names.

When I have long enough project name the `composeUp` task has some troubles with TCP port check.

See also a pull request with unit test that shows that:

- https://github.com/avast/gradle-docker-compose-plugin/pull/337

On my local machine with similar setup I can observe following messages:

```
[...]
Will use localhost as host of kafka
Waiting for TCP socket on localhost:9092 of 'kafka_1' (TCP connection on localhost:9092 of 'kafka_1' was disconnected right after connected)
Will use localhost as host of kafka
Going to replace container information of 'kafka_1' because port 9092 was exposed as 9092 but is null now
Waiting for TCP socket on localhost:null of 'kafka_1' (Could not find matching constructor for: java.net.Socket(String, null))
Will use localhost as host of kafka
[...]
```

**Comment by augi** [comment]
Hello, thank you for reporting this issue 👍 Also, feel free to prepare a fix, or at least share your opinion on why this could happen.

**Comment by augi** [comment]
So it actually looks like there is a problem with the Docker image, no? 🤔

**Comment by wiiitek** [comment]
> So it actually looks like there is a problem with the Docker image, no?

Yes, this specific docker image version **and** long project name.But I don't think it is worth investing time.
Because we can:

1. use shorter project name, or
2. use newer docker image
3. use different docker image ([wurstmeister/kafka](https://registry.hub.docker.com/r/wurstmeister/kafka/tags?page=1&name=2.4.1))

So it looks rather like a *known issue* to me. What do you think?
I'm ok with closing this task as well as linked pull request.

**Comment by augi** [comment]
Absolutely agree 👍 So I'm going to close this task and the related PR. We could reopen them if this issue became more prevalent.

Anyway, thank you very much for the time you invested to this contribution! 👍
