### ISSUE TITLE
Tasks to start each service?

### ISSUE THREAD

**Issue by robertfmurdock** [avast/gradle-docker-compose-plugin#340]
I've got a gradle multiproject where a few projects depend on only one of the services listed in my compose file, and for a while now I've been finding myself wishing I could configure this plugin so that each service could have its own "up" task, so I could loosen up the order of things happening (and only start the containers I need based on the task being triggered by gradle dependencies).

Does that make any sense? Any thought as to getting something like that on the roadmap?

**Comment by augi** [comment]
Hello, there is no such thing on the roadmap but if I understand your use-case correctly, it should be sufficient to specify the `startedServices` in each project, e.g.
```gradle
dockerCompose {
    startedServices = ['web']
}
```
Then you can use `composeUp`.

**Comment by robertfmurdock** [comment]
That... actually works pretty well!

Is that a way of using the API that is intended to be stable?
