### ISSUE TITLE
Enable Kotlin DSL

### ISSUE THREAD

**Issue by realulim** [avast/gradle-docker-compose-plugin#342]
Can this plugin be used at all with the Gradle Kotlin DSL? If yes, then it would be nice to have it in the docs, because the groovy way of configuring the plugin does not work with Kotlin.

**Comment by augi** [comment]
Hello, I personally don't use Kotlin DSL so I cannot verify this. But someone created a PR that describes how to use nested settings from Kotlin DSL, so I guess it is possible.

https://github.com/avast/gradle-docker-compose-plugin#nested-configurations

Feel free to prepare a PR updating the docs 🙏

**Comment by realulim** [comment]
Well, I haven't found a way to get it to work. But my Kotlin DSL knowledge is very limited.

**Comment by henrik242** [comment]
This plugin works great with the Kotlin DSL.  Here's an example from our codebase:
```
apply(plugin = "docker-compose")

configure<ComposeExtension> {
    includeDependencies.set(true)
    buildBeforeUp.set(false)
    buildBeforePull.set(false)
    waitForTcpPorts.set(false)

    createNested("local").apply {
        projectName = "foo"
        environment.putAll(mapOf("ENVIRONMENT" to "local"))
        startedServices.set(listOf("foo-api", "foo-integration"))
    }
    createNested("featureTest").apply {
        projectName = "foo"
        environment.putAll(
            mapOf(
                "ENVIRONMENT" to "local",
                "TAGS" to "feature-test,local"
            )
        )
        startedServices.set(listOf("foo-web"))
    }
    createNested("dev").apply {
        projectName = "foo"
        environment.putAll(mapOf("ENVIRONMENT" to "dev"))
        startedServices.set(listOf("foo-api"))
        upAdditionalArgs.set(listOf("--no-deps"))
    }
}
```

**Comment by augi** [comment]
@henrik242 Thank you very much for your example! 👍 I've just used it (slightly modified) as an example in README.

**Comment by realulim** [comment]
Could you please add an example for writing this in Kotlin:

dockerComposeStopTimeout = java.time.Duration.ofSeconds(20)

I simply have not found a way to access these java.time packages.

**Comment by realulim** [comment]
I got something like this:
  Line 83:     waitForTcpPortsTimeout.set(java.time.Duration.ofMinutes(1))
                                               ^ Unresolved reference: time

**Comment by realulim** [comment]
@henrik242 Sorry for the delay in answering. Here's the entirety of my project, just a minimal build.gradle.kts:

```
import com.avast.gradle.dockercompose.ComposeExtension

plugins {
    java
    id("com.avast.gradle.docker-compose") version("0.15.2")
}

configure<ComposeExtension> {
    waitForTcpPortsTimeout.set(java.time.Duration.ofSeconds(60))
}

```
Run this via ./gradlew clean (or something) and you will get the error:
```

Script compilation error:
  Line 9:     waitForTcpPortsTimeout.set(java.time.Duration.ofSeconds(60))
                                              ^ Unresolved reference: time
1 error
```
I am using Java 11 and Gradle 7.2 here.

**Comment by miikeat** [comment]
adding ```import java.time.Duration``` should do the trick
in your example its the ```java``` variable of gradle not the ```java``` package! Hence the "Unresolved reference" error

**Comment by realulim** [comment]
That worked, thank you! I did not know that I cannot write java.time.Duration in this Kotlin context!
