### ISSUE TITLE
Env variables and system properties are exposed under different name

### ISSUE THREAD

**Issue by Flame239** [avast/gradle-docker-compose-plugin#345]
If service name has dashes in docker-compose file (for example `web-service`), then plugin will expose env variables and system properties for this service under the name having dashes replaced with underscores (for example `web_service.host`).

Proposed fix is in https://github.com/avast/gradle-docker-compose-plugin/pull/344

**Comment by augi** [comment]
Fixed in `0.15.1`. Thank you! 👍
