### ISSUE TITLE
Multiple tasks composeUp/Down

### ISSUE THREAD

**Issue by s4s0l** [avast/gradle-docker-compose-plugin#36]
Hi,

First of all, great plug-in, simple yet powerful. There is plenty of gradle-docker plugins. Your was like fifth or sixth I've tried and decided not to look any further.

But i have a question, have you considered functionality of multiple compose configs in one gradle project?
Now its impossible to have two separate compose.ymls. One for let's say integration tests, and second for hmm other integration tests. 
I don't know if its clear. First set of tests are some units that test for example dao classes against some database which runs inside docker and is started by your plug-in. The second tests are full blown integration tests that require different compose.yml where application being developed is runn the way it will be running in production. 
Now its possible to accomplish it with multiple gradle projects. But I've discovered that your code is quite elastic and it is possible to do things like:

```
import com.avast.gradle.dockercompose.tasks.ComposeUp
task xxx(type: ComposeUp){
    extension = new com.avast.gradle.dockercompose.ComposeExtension(project, xxx,
            null);
    extension.useComposeFiles = ['src/test/docker/docker4test-sample/docker-compose.yml']

}
```

Then I can have second to composeUp task with it's own configuration.

So i think it's simple to make it work in less disgusting way, only problem is how to overcome fact that tasks need each other references (Up and Down), but imho doable. Would you consider such change? I'm asking because I don't know whether to prepare PR or just do it for myself by just wrapping your plug-in.

**Comment by augi** [comment]
Hi, I think your use-case is absolutely valid and it would be nice to have support for this in the plugin. Feel free to prepare a PR but it would be nice to discuss the API here before.

What about this? `dockerCompose.create('another-docker-compose.yaml', 'another')`

It would create `anotherDockerCompose` extension, `anotherComposeUp` task and `anotherComposeDown` task?

**Comment by s4s0l** [comment]
I was thinking more about something like:

```
dockerCompose {
    useComposeFiles = ['src/test/docker/docker-compose.yml']
    removeContainers = true
    isRequiredBy test
    integrationTests {
        useComposeFiles = ['src/integrationTest/docker/docker-compose.yml']
        removeVolumes = true
        isRequiredBy integrationTestTask
    }
    uiTests {
        useComposeFiles = ['src/uiTest/docker/docker-compose.yml']
        isRequiredBy uiTestTask
    }
}
```
It would be kind of inheritance. If you define anything at top level (dockerCompose) if it is not overriden in specific configuration it will be used as default for that configuration. Extra configurations can be enabled as closures defining new extensions. So in above example there will be dynammicaly created tasks integrationTestsComposeUp/Down and uiTestsComposeUp/Down. There could be a shorthand for that like:
```
dockerCompose {
    useComposeFiles = ['src/test/docker/docker-compose.yml']
    removeContainers = true
    isRequiredBy test
    integrationTests(['src/integrationTest/docker/docker-compose.yml'],integrationTestTask)
    uiTests(['src/uiTest/docker/docker-compose.yml'], uiTestTask)
    }
}
```
Because it will be the most common use case IMO. 
Or even:
```
dockerCompose {
    useComposeFiles = ['src/test/docker/docker-compose.yml']
    removeContainers = true
    isRequiredBy test
    isRequiredByIntegrationTests 'src/integrationTest/docker/docker-compose.yml'
    isRequiredByUiTests 'src/uiTest/docker/docker-compose.yml'
    }
}
```
Which would be more dslish. isRequiredByUiTests would wrapp arounf uiTests task with given ymls, which is actually your proposition but without need for '()'. 
What do you think?

**Comment by yegorius** [comment]
Hello everybody. Thank you @augi for developing this great plugin. It perfectly suits the needs of my team.
Just as @s4s0l , I also need to have multiple composeUp/Down tasks for a set of different compose files. I think the improvements which s4s0l has proposed are very convenient. It would be great to have them any time soon.

**Comment by hanscoder** [comment]
Hi. Thank you for the gread plugin. I have the same problem and would like to have multiple tasks. As I see it is still the question how the api should look like. What can we do to answer this question and have an api? 

Then I could also help to develop this new feature.

**Comment by andrcuns** [comment]
I'm willing to help as well since I have stumbled on the same problem and current solution in gradle to make it work with single set of tasks looks rather ugly.

**Comment by augi** [comment]
I hope I will have time in few weeks to implement this feature.

**Comment by TimothyJones** [comment]
I really like @s4s0l's suggestion, but in trying to get this going without a more principled approach, I stumbled on the following workaround: 

```
import com.avast.gradle.dockercompose.tasks.ComposeUp;
import com.avast.gradle.dockercompose.tasks.ComposePull
import com.avast.gradle.dockercompose.tasks.ComposeDown
import com.avast.gradle.dockercompose.ComposeExtension


ext.newCompose = { name ->
    ComposeUp upTask = project.tasks.create("${name}ComposeUp", ComposeUp)
    ComposePull pullTask = project.tasks.create("${name}ComposePull", ComposePull)
    ComposeDown downTask = project.tasks.create("${name}ComposeDown", ComposeDown)
    ComposeExtension extension = project.extensions.create("${name}Compose", ComposeExtension, project, upTask, downTask)
    upTask.extension = extension
    upTask.downTask = downTask
    downTask.extension = extension
    pullTask.extension = extension
}
```

Then you use it like so:

```
newCompose("db")

dbCompose {
    startedServices = ['db']
}
```

it would be fairly simple to extend the existing plugin so that it exposes this method (and the current `apply` called it) providing essentially the functionality that @augi suggested:

```
dockerCompose.create("db")
dbCompose {
    startedServices = ['db']
    /* other config here */
}
```

I'm happy to make a pull request if it would be accepted, but I don't want to prevent @s4s0l's nicer approach from being included in the future (sadly I don't have the time to contribute a solution with the nicer DSL).

**Comment by augi** [comment]
I'll try to prepare the PL with the DSL during this weekend.

**Comment by augi** [comment]
I refactored the code so the implementation should be even easier.

I [read](https://stackoverflow.com/questions/17626607/writing-gradle-plugin-with-nested-extension-objects) [various](https://stackoverflow.com/questions/28999106/define-nested-extension-containers-in-gradle) [articles](http://mrhaki.blogspot.cz/2016/02/gradle-goodness-create-objects-with-dsl.html) [how to do DSL](http://mrhaki.blogspot.cz/2016/02/gradle-goodness-using-nested-domain.html) I will probably use [methodMissing()](http://mrhaki.blogspot.cz/2009/11/groovy-goodness-create-dynamic-methods.html) with [Project.configure()](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#configure(java.lang.Object,%20groovy.lang.Closure))

**Comment by augi** [comment]
It's finally done - `0.6.0`

**Comment by TimothyJones** [comment]
Very much appreciated! I'll check it out this week.
