### ISSUE TITLE
how to change composeUp environment variables?

### ISSUE THREAD

**Issue by pedro-abundio-wang** [avast/gradle-docker-compose-plugin#364]
![image](https://user-images.githubusercontent.com/50159788/178665056-6a53a7ed-b946-410b-a968-1a4d35d34f89.png)

how to set USE_DB_ID and USE_JSON_PAYLOAD_AND_HEADERS value in gradle command line, what should i do? 

`./gradlew :events-db:events-postgres:composeUp -DUSE_DB_ID=true -DUSE_JSON_PAYLOAD_AND_HEADERS=false`

or

`./gradlew :events-db:events-postgres:composeUp -PUSE_DB_ID=true -PUSE_JSON_PAYLOAD_AND_HEADERS=false`

**Comment by augi** [comment]
Hello, when the plugin executes Docker Compose, it combines current environment variables and environment variables explicitly set. See [this code](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L80).

So it is sufficient to ensure the environment variables are available for Gradle (please refer to the Gradle documentation).

> Please note that `-D` sets _JVM system variable_, not environment variable. My guess is that you should have something like `USE_DB_ID=true USE_JSON_PAYLOAD_AND_HEADERS=false ./gradlew :events-db:events-postgres:composeUp`
