### ISSUE TITLE
is there a way to only pipe ERROR logs to captureContainersOutput?

### ISSUE THREAD

**Issue by 90abyss** [avast/gradle-docker-compose-plugin#366]
not an issue but more of a feature request.

i only want to show ERROR logs on the console when I turn on captureContainersOutput. is there a way to do that?

**Comment by augi** [comment]
Hello,

the capturing is perfomed [here](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L171). So as you can see, the plugin just executes Docker Compose with `logs -f`, and redirects output from this command.

Unfortunatelly, Docker Compose doesn't allow to distinguish betweet stdout and stderr: https://docs.docker.com/engine/reference/commandline/compose_logs/
