### ISSUE TITLE
Support authoruzation to private registry

### ISSUE THREAD

**Issue by mtovt** [avast/gradle-docker-compose-plugin#375]
HelloI found no place to ask a question. Sorry if it wrong place for this.

Is there a way to authorize using this plugin? Seems Gradle task to perform login (`docker login`) to a private registry using the plugin may be useful. Does it have a chance to be implemented?

 Thanks for this plugin!

**Comment by augi** [comment]
Hello, `docker login` is not supported by this plugin, it supposes the `docker` and `docker-compose` commands are ready to be used.

I'm not going to implement this myself but feel free to prepare a new PR to add this new feature. It shouldn't be so hard.
