### ISSUE TITLE
Remove images by Gradle task

### ISSUE THREAD

**Issue by mtovt** [avast/gradle-docker-compose-plugin#376]
Is there a way to remove (unused/all) docker images using this plugin? Seems Gradle task for this action may be useful. Does it have a chance to be implemented?

Seems `removeImages = RemoveImages.All` doesn't work after `composePush` Gradle task. Is there a way to do it?

**Comment by augi** [comment]
Hello,

this plugin removes the images as part of `composeDown`, and only if `startedServices` is not specified, see [the code](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeDownForced.groovy#L67).

This follows the main use-case of this plugin, so to simplify integration testing with Docker Compose. So typically, you use `composeDown` at the end.
