### ISSUE TITLE
Support docker compose profile option

### ISSUE THREAD

**Issue by michaelruocco** [avast/gradle-docker-compose-plugin#377]
It would be useful if the plugin was able to support configuring the [profiles option](https://docs.docker.com/compose/profiles/) to helps selecting specific services to run without having to explicitly specify the names of all the services.

I have had a scan through the docs and code and it doesn't look like this is possible, are there any plans to add support for profiles at all?

**Comment by augi** [comment]
Hello, this plugin is just a thin wrapper around `docker-compose` command and you can specify any additional parameters using `composeAdditionalArgs`.

If you believe it would be valuable to have an explicit support in this plugin, feel free to prepare a new PR (it should be easy) 🙏
