### ISSUE TITLE
Add supported `docker` and `docker-compose` versions and explicitly check them

### ISSUE THREAD

**Issue by mtovt** [avast/gradle-docker-compose-plugin#381]
Hello! I'd faced an incompatible docker-compose version. Seems it would be nice to have explicit `docker` and `docker-compose` versions checked by the plugin before interacting.

**Comment by augi** [comment]
Hello, have you encountered any issues with specific docker[-compose] versions that are not supported by this plugin, please? Could you please share them? Thanks!

**Comment by mtovt** [comment]
Hello! Sorry, I didn't remember what happened or what versions have been used. I remember an upgrade of `docker-compose` has helped. I should attach them right away next time.
