### ISSUE TITLE
Migration to V2 `docker compose` 

### ISSUE THREAD

**Issue by rt-works** [avast/gradle-docker-compose-plugin#401]
Are there any plans to support `docker compose` instead of `docker-compose`? Some docker images doesn't support anymore the `docker-compose` command so that the `gradle-docker-compose-plugin` isn't really usable any more https://docs.docker.com/compose/migrate/

**Comment by augi** [comment]
Hello, I'm not aware of anyone who is preparing a PR for support of this. Feel free to prepare a new PR yourself 🙏

**Comment by augi** [comment]
Duplicates #322
