### ISSUE TITLE
Setting environment variables lazily or in the execution phase?

### ISSUE THREAD

**Issue by henrik242** [avast/gradle-docker-compose-plugin#426]
I've got this config in my project:
```
configure<ComposeExtension> {
    createNested("dev").apply {
        environment.put("DB_PASSWORD", VaultUtil.read("DB_PASSWORD")),
        startedServices.set(listOf("my-api"))
    }
}
tasks {
    register("runDocker") {
        dependsOn(composeBuild)
        when {
            rootProject.hasProperty("dev") -> dependsOn(devComposeUp)
            rootProject.hasProperty("prod") -> dependsOn(prodComposeUp)
            else -> dependsOn(localComposeUp)
        }
    }
}
```
`VaultUtil.read` is *only* needed when I run `gradle runDocker -Pdev`, but since `createNested` is done in Gradle's configuration phase it is always run regardless of task.

Is there a way to only set the environment variables when that specific task is run?

**Comment by henrik242** [comment]
Any ideas @augi ?

**Comment by augi** [comment]
Hello, this is a valid question 👌 My only idea is to configure the task created by the nested settings lazily, using the `configure` function:  https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by henrik242** [comment]
I solved it by using the `Provider` argument to `putAll`: 
```
configure<ComposeExtension> {
    createNested("dev").apply {
        environment.putAll(
            provider {
                "DB_PASSWORD" to VaultUtil.read("DB_PASSWORD")
            }
        )
        startedServices.set(listOf("my-api"))
    }
}```
