### ISSUE TITLE
Older version of the plugin not available on maven anymore

### ISSUE THREAD

**Issue by peterzhuamazon** [avast/gradle-docker-compose-plugin#446]
Hi,

https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/

![Screenshot 2024-07-18 at 7 33 29 PM](https://github.com/user-attachments/assets/37dea215-ad0a-4a54-a240-e5e1b89050e7)

As we can see versions such as 0.12 are not available on maven central anymore.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not find com.avast.gradle:gradle-docker-compose-plugin:0.12.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.12.1/gradle-docker-compose-plugin-0.12.1.pom
       - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.12.1/gradle-docker-compose-plugin-0.12.1.pom
     Required by:
         project :buildSrc

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/
```

Thanks.

**Comment by augi** [comment]
Hi, thanks for your report! The older versions was published to JCentral, which is decommissioned now, this is why you cannot see the versions before switch from JCentral to Maven Central.

If you want to use an older version, the default way, so using the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/com.avast.gradle.docker-compose), works even for them.
