### ISSUE TITLE
Old version <0.14.2 not found in MavenCentral

### ISSUE THREAD

**Issue by sonnyhcl** [avast/gradle-docker-compose-plugin#447]
Hi, I want to report an issue that old version <0.14.2 not found in MavenCentral repository.

https://repo1.maven.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/
![image](https://github.com/user-attachments/assets/13b1e8a6-bb7a-4a32-9c98-439575245c9c)

**Comment by augi** [comment]
Hello, it is a duplicate, please see https://github.com/avast/gradle-docker-compose-plugin/issues/446

It is documented in the README.

**Comment by sonnyhcl** [comment]
@augi Sorry old versions are also missing from GPP now.
As Gradle Plugin Portal claim [they just proxy Maven Central instead of JCenter from this blog](https://blog.gradle.org/portal-jcenter-impact) ~2 weeks ago, Gradle Plugin Portal doesn't have any copy for old version of docker-compose.gradle.plugin as well. I can only find pom for old version without jar.

[![image](https://github.com/user-attachments/assets/b3e58ca7-e83d-4f48-ab68-8bdea27a3fdb)](https://plugins.gradle.org/m2/com/avast/gradle/docker-compose/com.avast.gradle.docker-compose.gradle.plugin/0.8.12/)

**Comment by augi** [comment]
Hi, thank you for pointing this out! I wasn't aware of this, so I've just added [a note about unavailability of the older version](https://github.com/avast/gradle-docker-compose-plugin/commit/82b9e02d5a79dc94ead743f66aeaaa4307df4459). Thank you!
