### ISSUE TITLE
Define services to be started 

### ISSUE THREAD

**Issue by bastman** [avast/gradle-docker-compose-plugin#87]
Thanks for the great plugin.

I just wonder if there is a chance to get a features that allows selecting services from a docker-compose.yml (e.g.: web, db -vs- web)

Currently, I would need to hack around by specifying a collection of compose.yml files. It feels weird somehow.

**Comment by augi** [comment]
Hi,

I'm not sure if I understand the question. Do you want to be able to execute just selected services from your `docker-compose.yml` file?

As the plugin uses the `docker-compose` command and this command doesn't support this feature, I'm afraid that I'm not able to implement it :( If you know how to achieve it, please let me know.

**Comment by bastman** [comment]
Hi Augi, docker-compose supports that feature.

e.g.: $ docker-compose -f stack.yml up db (starts service "db" defined in compose-file "stack.yml")

**Comment by augi** [comment]
Ah, thanks! I wasn't aware of this feature.

Anyway - I'm now looking for a way how to customize all the commands executed because it doesn't make sense to make a change in plugin because of these requests.

**Comment by bastman** [comment]
Nice. Thanks a lot. I'm looking forward :)

**Comment by augi** [comment]
I added `startedService` property to the extension - it's in `0.5.1`. Please note that I had to change name of the plugin so you must also update the name of plugin dependency.
