### ISSUE TITLE
Extension to check if container is ready

### ISSUE THREAD

**Issue by stgunholy** [avast/gradle-docker-compose-plugin#94]
First of all thank you for a wonderful work you are doing. 
I have a suggestion though on possible extension of your plugin. 
I am using it for running IT tests for application deployed on WildFly. Unfortunately it exposes 8080 port way earlier then application is actually ready to receive calls. What I suggest is to add something like 

```
 void waitForOkHttp(Map<String, String> urlsToWait, Iterable<ServiceInfo> servicesInfos) {
        Map<String, Integer> servicePorts = [:]

        servicesInfos.forEach { serviceInfo ->
            servicePorts.put(serviceInfo.name, serviceInfo.getTcpPort())
        }

        urlsToWait.forEach { service, u ->
            def urlStr = "http://localhost:" + servicePorts.get(service) + u;
            logger.lifecycle("Waiting for url of service: ${service} to return 200 response status on url: ${urlStr}")

            URL url = new URL(urlStr);

            while (true) {
                logger.info("Waiting...")

                try {
                    HttpURLConnection http = (HttpURLConnection)url.openConnection();
                    int statusCode = http.getResponseCode();

                    if (statusCode < 400) {
                        logger.lifecycle("Service: ${service}, url: ${urlStr} replied with 200.")
                        break;
                    }
                    else {
                        sleep(5000)
                    }
                }
                catch (Exception ex) {
                    sleep(5000)
                }
            }
        }
    }
```

into UpTask and extend configuration with parameter:
```
 waitForOkHttp = [
        "application-cotainer": "/rest/ping"
    ]
```

this will allow to "wait" while application running on application servers is actually ready to receive the calls.

**Comment by augi** [comment]
Hi, thanks for the suggestion! I understand that this can be the main use-case for many applications but isn't the [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction sufficient? It's a standard way how to perform healthchecks...

Anyway, if you prepare a PR then I will happily accept it.

**Comment by augi** [comment]
I think that this should be handled on lower level - use the `HEALTHCHECK` instruction in `Dockerfile` or [healtcheck in docker-compose.yml](https://docs.docker.com/compose/compose-file/#healthcheck).

This would be better because it allows to use the Docker Compose file also without the plugin.
